package com.pro.proyectospro.configuracion.domain;

public class Atarea {

	private Pfase pfase;

	public Pfase getPfase() {
		return pfase;
	}

	public void setPfase(Pfase pfase) {
		this.pfase = pfase;
	}
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column atarea.codigo
	 * @mbggenerated
	 */
	private Integer codigo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column atarea.codATareaPadre
	 * @mbggenerated
	 */
	private Integer codatareapadre;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column atarea.codEstado
	 * @mbggenerated
	 */
	private Integer codestado;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column atarea.codPFase
	 * @mbggenerated
	 */
	private Integer codpfase;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column atarea.codArea
	 * @mbggenerated
	 */
	private Integer codarea;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column atarea.fechaInicioPr
	 * @mbggenerated
	 */
	private String fechainiciopr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column atarea.fechaFinPr
	 * @mbggenerated
	 */
	private String fechafinpr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column atarea.fechaInicioPu
	 * @mbggenerated
	 */
	private String fechainiciopu;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column atarea.fechaFinPu
	 * @mbggenerated
	 */
	private String fechafinpu;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column atarea.fechaInicioRe
	 * @mbggenerated
	 */
	private String fechainiciore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column atarea.fechaFinRe
	 * @mbggenerated
	 */
	private String fechafinre;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column atarea.des
	 * @mbggenerated
	 */
	private String des;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column atarea.activo
	 * @mbggenerated
	 */
	private Boolean activo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column atarea.codigo
	 * @return  the value of atarea.codigo
	 * @mbggenerated
	 */
	public Integer getCodigo() {
		return codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column atarea.codigo
	 * @param codigo  the value for atarea.codigo
	 * @mbggenerated
	 */
	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column atarea.codATareaPadre
	 * @return  the value of atarea.codATareaPadre
	 * @mbggenerated
	 */
	public Integer getCodatareapadre() {
		return codatareapadre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column atarea.codATareaPadre
	 * @param codatareapadre  the value for atarea.codATareaPadre
	 * @mbggenerated
	 */
	public void setCodatareapadre(Integer codatareapadre) {
		this.codatareapadre = codatareapadre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column atarea.codEstado
	 * @return  the value of atarea.codEstado
	 * @mbggenerated
	 */
	public Integer getCodestado() {
		return codestado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column atarea.codEstado
	 * @param codestado  the value for atarea.codEstado
	 * @mbggenerated
	 */
	public void setCodestado(Integer codestado) {
		this.codestado = codestado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column atarea.codPFase
	 * @return  the value of atarea.codPFase
	 * @mbggenerated
	 */
	public Integer getCodpfase() {
		return codpfase;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column atarea.codPFase
	 * @param codpfase  the value for atarea.codPFase
	 * @mbggenerated
	 */
	public void setCodpfase(Integer codpfase) {
		this.codpfase = codpfase;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column atarea.codArea
	 * @return  the value of atarea.codArea
	 * @mbggenerated
	 */
	public Integer getCodarea() {
		return codarea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column atarea.codArea
	 * @param codarea  the value for atarea.codArea
	 * @mbggenerated
	 */
	public void setCodarea(Integer codarea) {
		this.codarea = codarea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column atarea.fechaInicioPr
	 * @return  the value of atarea.fechaInicioPr
	 * @mbggenerated
	 */
	public String getFechainiciopr() {
		return fechainiciopr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column atarea.fechaInicioPr
	 * @param fechainiciopr  the value for atarea.fechaInicioPr
	 * @mbggenerated
	 */
	public void setFechainiciopr(String fechainiciopr) {
		this.fechainiciopr = fechainiciopr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column atarea.fechaFinPr
	 * @return  the value of atarea.fechaFinPr
	 * @mbggenerated
	 */
	public String getFechafinpr() {
		return fechafinpr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column atarea.fechaFinPr
	 * @param fechafinpr  the value for atarea.fechaFinPr
	 * @mbggenerated
	 */
	public void setFechafinpr(String fechafinpr) {
		this.fechafinpr = fechafinpr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column atarea.fechaInicioPu
	 * @return  the value of atarea.fechaInicioPu
	 * @mbggenerated
	 */
	public String getFechainiciopu() {
		return fechainiciopu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column atarea.fechaInicioPu
	 * @param fechainiciopu  the value for atarea.fechaInicioPu
	 * @mbggenerated
	 */
	public void setFechainiciopu(String fechainiciopu) {
		this.fechainiciopu = fechainiciopu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column atarea.fechaFinPu
	 * @return  the value of atarea.fechaFinPu
	 * @mbggenerated
	 */
	public String getFechafinpu() {
		return fechafinpu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column atarea.fechaFinPu
	 * @param fechafinpu  the value for atarea.fechaFinPu
	 * @mbggenerated
	 */
	public void setFechafinpu(String fechafinpu) {
		this.fechafinpu = fechafinpu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column atarea.fechaInicioRe
	 * @return  the value of atarea.fechaInicioRe
	 * @mbggenerated
	 */
	public String getFechainiciore() {
		return fechainiciore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column atarea.fechaInicioRe
	 * @param fechainiciore  the value for atarea.fechaInicioRe
	 * @mbggenerated
	 */
	public void setFechainiciore(String fechainiciore) {
		this.fechainiciore = fechainiciore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column atarea.fechaFinRe
	 * @return  the value of atarea.fechaFinRe
	 * @mbggenerated
	 */
	public String getFechafinre() {
		return fechafinre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column atarea.fechaFinRe
	 * @param fechafinre  the value for atarea.fechaFinRe
	 * @mbggenerated
	 */
	public void setFechafinre(String fechafinre) {
		this.fechafinre = fechafinre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column atarea.des
	 * @return  the value of atarea.des
	 * @mbggenerated
	 */
	public String getDes() {
		return des;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column atarea.des
	 * @param des  the value for atarea.des
	 * @mbggenerated
	 */
	public void setDes(String des) {
		this.des = des;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column atarea.activo
	 * @return  the value of atarea.activo
	 * @mbggenerated
	 */
	public Boolean getActivo() {
		return activo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column atarea.activo
	 * @param activo  the value for atarea.activo
	 * @mbggenerated
	 */
	public void setActivo(Boolean activo) {
		this.activo = activo;
	}
}