package com.pro.proyectospro.configuracion.domain;

import java.util.ArrayList;
import java.util.List;

public class AtareaExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table atarea
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table atarea
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table atarea
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table atarea
	 * @mbggenerated
	 */
	public AtareaExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table atarea
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table atarea
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table atarea
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table atarea
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table atarea
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table atarea
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table atarea
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table atarea
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table atarea
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table atarea
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table atarea
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCodigoIsNull() {
			addCriterion("codigo is null");
			return (Criteria) this;
		}

		public Criteria andCodigoIsNotNull() {
			addCriterion("codigo is not null");
			return (Criteria) this;
		}

		public Criteria andCodigoEqualTo(Integer value) {
			addCriterion("codigo =", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoNotEqualTo(Integer value) {
			addCriterion("codigo <>", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoGreaterThan(Integer value) {
			addCriterion("codigo >", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoGreaterThanOrEqualTo(Integer value) {
			addCriterion("codigo >=", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoLessThan(Integer value) {
			addCriterion("codigo <", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoLessThanOrEqualTo(Integer value) {
			addCriterion("codigo <=", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoIn(List<Integer> values) {
			addCriterion("codigo in", values, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoNotIn(List<Integer> values) {
			addCriterion("codigo not in", values, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoBetween(Integer value1, Integer value2) {
			addCriterion("codigo between", value1, value2, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoNotBetween(Integer value1, Integer value2) {
			addCriterion("codigo not between", value1, value2, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodatareapadreIsNull() {
			addCriterion("codATareaPadre is null");
			return (Criteria) this;
		}

		public Criteria andCodatareapadreIsNotNull() {
			addCriterion("codATareaPadre is not null");
			return (Criteria) this;
		}

		public Criteria andCodatareapadreEqualTo(Integer value) {
			addCriterion("codATareaPadre =", value, "codatareapadre");
			return (Criteria) this;
		}

		public Criteria andCodatareapadreNotEqualTo(Integer value) {
			addCriterion("codATareaPadre <>", value, "codatareapadre");
			return (Criteria) this;
		}

		public Criteria andCodatareapadreGreaterThan(Integer value) {
			addCriterion("codATareaPadre >", value, "codatareapadre");
			return (Criteria) this;
		}

		public Criteria andCodatareapadreGreaterThanOrEqualTo(Integer value) {
			addCriterion("codATareaPadre >=", value, "codatareapadre");
			return (Criteria) this;
		}

		public Criteria andCodatareapadreLessThan(Integer value) {
			addCriterion("codATareaPadre <", value, "codatareapadre");
			return (Criteria) this;
		}

		public Criteria andCodatareapadreLessThanOrEqualTo(Integer value) {
			addCriterion("codATareaPadre <=", value, "codatareapadre");
			return (Criteria) this;
		}

		public Criteria andCodatareapadreIn(List<Integer> values) {
			addCriterion("codATareaPadre in", values, "codatareapadre");
			return (Criteria) this;
		}

		public Criteria andCodatareapadreNotIn(List<Integer> values) {
			addCriterion("codATareaPadre not in", values, "codatareapadre");
			return (Criteria) this;
		}

		public Criteria andCodatareapadreBetween(Integer value1, Integer value2) {
			addCriterion("codATareaPadre between", value1, value2,
					"codatareapadre");
			return (Criteria) this;
		}

		public Criteria andCodatareapadreNotBetween(Integer value1,
				Integer value2) {
			addCriterion("codATareaPadre not between", value1, value2,
					"codatareapadre");
			return (Criteria) this;
		}

		public Criteria andCodestadoIsNull() {
			addCriterion("codEstado is null");
			return (Criteria) this;
		}

		public Criteria andCodestadoIsNotNull() {
			addCriterion("codEstado is not null");
			return (Criteria) this;
		}

		public Criteria andCodestadoEqualTo(Integer value) {
			addCriterion("codEstado =", value, "codestado");
			return (Criteria) this;
		}

		public Criteria andCodestadoNotEqualTo(Integer value) {
			addCriterion("codEstado <>", value, "codestado");
			return (Criteria) this;
		}

		public Criteria andCodestadoGreaterThan(Integer value) {
			addCriterion("codEstado >", value, "codestado");
			return (Criteria) this;
		}

		public Criteria andCodestadoGreaterThanOrEqualTo(Integer value) {
			addCriterion("codEstado >=", value, "codestado");
			return (Criteria) this;
		}

		public Criteria andCodestadoLessThan(Integer value) {
			addCriterion("codEstado <", value, "codestado");
			return (Criteria) this;
		}

		public Criteria andCodestadoLessThanOrEqualTo(Integer value) {
			addCriterion("codEstado <=", value, "codestado");
			return (Criteria) this;
		}

		public Criteria andCodestadoIn(List<Integer> values) {
			addCriterion("codEstado in", values, "codestado");
			return (Criteria) this;
		}

		public Criteria andCodestadoNotIn(List<Integer> values) {
			addCriterion("codEstado not in", values, "codestado");
			return (Criteria) this;
		}

		public Criteria andCodestadoBetween(Integer value1, Integer value2) {
			addCriterion("codEstado between", value1, value2, "codestado");
			return (Criteria) this;
		}

		public Criteria andCodestadoNotBetween(Integer value1, Integer value2) {
			addCriterion("codEstado not between", value1, value2, "codestado");
			return (Criteria) this;
		}

		public Criteria andCodpfaseIsNull() {
			addCriterion("codPFase is null");
			return (Criteria) this;
		}

		public Criteria andCodpfaseIsNotNull() {
			addCriterion("codPFase is not null");
			return (Criteria) this;
		}

		public Criteria andCodpfaseEqualTo(Integer value) {
			addCriterion("codPFase =", value, "codpfase");
			return (Criteria) this;
		}

		public Criteria andCodpfaseNotEqualTo(Integer value) {
			addCriterion("codPFase <>", value, "codpfase");
			return (Criteria) this;
		}

		public Criteria andCodpfaseGreaterThan(Integer value) {
			addCriterion("codPFase >", value, "codpfase");
			return (Criteria) this;
		}

		public Criteria andCodpfaseGreaterThanOrEqualTo(Integer value) {
			addCriterion("codPFase >=", value, "codpfase");
			return (Criteria) this;
		}

		public Criteria andCodpfaseLessThan(Integer value) {
			addCriterion("codPFase <", value, "codpfase");
			return (Criteria) this;
		}

		public Criteria andCodpfaseLessThanOrEqualTo(Integer value) {
			addCriterion("codPFase <=", value, "codpfase");
			return (Criteria) this;
		}

		public Criteria andCodpfaseIn(List<Integer> values) {
			addCriterion("codPFase in", values, "codpfase");
			return (Criteria) this;
		}

		public Criteria andCodpfaseNotIn(List<Integer> values) {
			addCriterion("codPFase not in", values, "codpfase");
			return (Criteria) this;
		}

		public Criteria andCodpfaseBetween(Integer value1, Integer value2) {
			addCriterion("codPFase between", value1, value2, "codpfase");
			return (Criteria) this;
		}

		public Criteria andCodpfaseNotBetween(Integer value1, Integer value2) {
			addCriterion("codPFase not between", value1, value2, "codpfase");
			return (Criteria) this;
		}

		public Criteria andCodareaIsNull() {
			addCriterion("codArea is null");
			return (Criteria) this;
		}

		public Criteria andCodareaIsNotNull() {
			addCriterion("codArea is not null");
			return (Criteria) this;
		}

		public Criteria andCodareaEqualTo(Integer value) {
			addCriterion("codArea =", value, "codarea");
			return (Criteria) this;
		}

		public Criteria andCodareaNotEqualTo(Integer value) {
			addCriterion("codArea <>", value, "codarea");
			return (Criteria) this;
		}

		public Criteria andCodareaGreaterThan(Integer value) {
			addCriterion("codArea >", value, "codarea");
			return (Criteria) this;
		}

		public Criteria andCodareaGreaterThanOrEqualTo(Integer value) {
			addCriterion("codArea >=", value, "codarea");
			return (Criteria) this;
		}

		public Criteria andCodareaLessThan(Integer value) {
			addCriterion("codArea <", value, "codarea");
			return (Criteria) this;
		}

		public Criteria andCodareaLessThanOrEqualTo(Integer value) {
			addCriterion("codArea <=", value, "codarea");
			return (Criteria) this;
		}

		public Criteria andCodareaIn(List<Integer> values) {
			addCriterion("codArea in", values, "codarea");
			return (Criteria) this;
		}

		public Criteria andCodareaNotIn(List<Integer> values) {
			addCriterion("codArea not in", values, "codarea");
			return (Criteria) this;
		}

		public Criteria andCodareaBetween(Integer value1, Integer value2) {
			addCriterion("codArea between", value1, value2, "codarea");
			return (Criteria) this;
		}

		public Criteria andCodareaNotBetween(Integer value1, Integer value2) {
			addCriterion("codArea not between", value1, value2, "codarea");
			return (Criteria) this;
		}

		public Criteria andFechainicioprIsNull() {
			addCriterion("fechaInicioPr is null");
			return (Criteria) this;
		}

		public Criteria andFechainicioprIsNotNull() {
			addCriterion("fechaInicioPr is not null");
			return (Criteria) this;
		}

		public Criteria andFechainicioprEqualTo(String value) {
			addCriterion("fechaInicioPr =", value, "fechainiciopr");
			return (Criteria) this;
		}

		public Criteria andFechainicioprNotEqualTo(String value) {
			addCriterion("fechaInicioPr <>", value, "fechainiciopr");
			return (Criteria) this;
		}

		public Criteria andFechainicioprGreaterThan(String value) {
			addCriterion("fechaInicioPr >", value, "fechainiciopr");
			return (Criteria) this;
		}

		public Criteria andFechainicioprGreaterThanOrEqualTo(String value) {
			addCriterion("fechaInicioPr >=", value, "fechainiciopr");
			return (Criteria) this;
		}

		public Criteria andFechainicioprLessThan(String value) {
			addCriterion("fechaInicioPr <", value, "fechainiciopr");
			return (Criteria) this;
		}

		public Criteria andFechainicioprLessThanOrEqualTo(String value) {
			addCriterion("fechaInicioPr <=", value, "fechainiciopr");
			return (Criteria) this;
		}

		public Criteria andFechainicioprIn(List<String> values) {
			addCriterion("fechaInicioPr in", values, "fechainiciopr");
			return (Criteria) this;
		}

		public Criteria andFechainicioprNotIn(List<String> values) {
			addCriterion("fechaInicioPr not in", values, "fechainiciopr");
			return (Criteria) this;
		}

		public Criteria andFechainicioprBetween(String value1, String value2) {
			addCriterion("fechaInicioPr between", value1, value2,
					"fechainiciopr");
			return (Criteria) this;
		}

		public Criteria andFechainicioprNotBetween(String value1, String value2) {
			addCriterion("fechaInicioPr not between", value1, value2,
					"fechainiciopr");
			return (Criteria) this;
		}

		public Criteria andFechafinprIsNull() {
			addCriterion("fechaFinPr is null");
			return (Criteria) this;
		}

		public Criteria andFechafinprIsNotNull() {
			addCriterion("fechaFinPr is not null");
			return (Criteria) this;
		}

		public Criteria andFechafinprEqualTo(String value) {
			addCriterion("fechaFinPr =", value, "fechafinpr");
			return (Criteria) this;
		}

		public Criteria andFechafinprNotEqualTo(String value) {
			addCriterion("fechaFinPr <>", value, "fechafinpr");
			return (Criteria) this;
		}

		public Criteria andFechafinprGreaterThan(String value) {
			addCriterion("fechaFinPr >", value, "fechafinpr");
			return (Criteria) this;
		}

		public Criteria andFechafinprGreaterThanOrEqualTo(String value) {
			addCriterion("fechaFinPr >=", value, "fechafinpr");
			return (Criteria) this;
		}

		public Criteria andFechafinprLessThan(String value) {
			addCriterion("fechaFinPr <", value, "fechafinpr");
			return (Criteria) this;
		}

		public Criteria andFechafinprLessThanOrEqualTo(String value) {
			addCriterion("fechaFinPr <=", value, "fechafinpr");
			return (Criteria) this;
		}

		public Criteria andFechafinprIn(List<String> values) {
			addCriterion("fechaFinPr in", values, "fechafinpr");
			return (Criteria) this;
		}

		public Criteria andFechafinprNotIn(List<String> values) {
			addCriterion("fechaFinPr not in", values, "fechafinpr");
			return (Criteria) this;
		}

		public Criteria andFechafinprBetween(String value1, String value2) {
			addCriterion("fechaFinPr between", value1, value2, "fechafinpr");
			return (Criteria) this;
		}

		public Criteria andFechafinprNotBetween(String value1, String value2) {
			addCriterion("fechaFinPr not between", value1, value2, "fechafinpr");
			return (Criteria) this;
		}

		public Criteria andFechainiciopuIsNull() {
			addCriterion("fechaInicioPu is null");
			return (Criteria) this;
		}

		public Criteria andFechainiciopuIsNotNull() {
			addCriterion("fechaInicioPu is not null");
			return (Criteria) this;
		}

		public Criteria andFechainiciopuEqualTo(String value) {
			addCriterion("fechaInicioPu =", value, "fechainiciopu");
			return (Criteria) this;
		}

		public Criteria andFechainiciopuNotEqualTo(String value) {
			addCriterion("fechaInicioPu <>", value, "fechainiciopu");
			return (Criteria) this;
		}

		public Criteria andFechainiciopuGreaterThan(String value) {
			addCriterion("fechaInicioPu >", value, "fechainiciopu");
			return (Criteria) this;
		}

		public Criteria andFechainiciopuGreaterThanOrEqualTo(String value) {
			addCriterion("fechaInicioPu >=", value, "fechainiciopu");
			return (Criteria) this;
		}

		public Criteria andFechainiciopuLessThan(String value) {
			addCriterion("fechaInicioPu <", value, "fechainiciopu");
			return (Criteria) this;
		}

		public Criteria andFechainiciopuLessThanOrEqualTo(String value) {
			addCriterion("fechaInicioPu <=", value, "fechainiciopu");
			return (Criteria) this;
		}

		public Criteria andFechainiciopuIn(List<String> values) {
			addCriterion("fechaInicioPu in", values, "fechainiciopu");
			return (Criteria) this;
		}

		public Criteria andFechainiciopuNotIn(List<String> values) {
			addCriterion("fechaInicioPu not in", values, "fechainiciopu");
			return (Criteria) this;
		}

		public Criteria andFechainiciopuBetween(String value1, String value2) {
			addCriterion("fechaInicioPu between", value1, value2,
					"fechainiciopu");
			return (Criteria) this;
		}

		public Criteria andFechainiciopuNotBetween(String value1, String value2) {
			addCriterion("fechaInicioPu not between", value1, value2,
					"fechainiciopu");
			return (Criteria) this;
		}

		public Criteria andFechafinpuIsNull() {
			addCriterion("fechaFinPu is null");
			return (Criteria) this;
		}

		public Criteria andFechafinpuIsNotNull() {
			addCriterion("fechaFinPu is not null");
			return (Criteria) this;
		}

		public Criteria andFechafinpuEqualTo(String value) {
			addCriterion("fechaFinPu =", value, "fechafinpu");
			return (Criteria) this;
		}

		public Criteria andFechafinpuNotEqualTo(String value) {
			addCriterion("fechaFinPu <>", value, "fechafinpu");
			return (Criteria) this;
		}

		public Criteria andFechafinpuGreaterThan(String value) {
			addCriterion("fechaFinPu >", value, "fechafinpu");
			return (Criteria) this;
		}

		public Criteria andFechafinpuGreaterThanOrEqualTo(String value) {
			addCriterion("fechaFinPu >=", value, "fechafinpu");
			return (Criteria) this;
		}

		public Criteria andFechafinpuLessThan(String value) {
			addCriterion("fechaFinPu <", value, "fechafinpu");
			return (Criteria) this;
		}

		public Criteria andFechafinpuLessThanOrEqualTo(String value) {
			addCriterion("fechaFinPu <=", value, "fechafinpu");
			return (Criteria) this;
		}

		public Criteria andFechafinpuIn(List<String> values) {
			addCriterion("fechaFinPu in", values, "fechafinpu");
			return (Criteria) this;
		}

		public Criteria andFechafinpuNotIn(List<String> values) {
			addCriterion("fechaFinPu not in", values, "fechafinpu");
			return (Criteria) this;
		}

		public Criteria andFechafinpuBetween(String value1, String value2) {
			addCriterion("fechaFinPu between", value1, value2, "fechafinpu");
			return (Criteria) this;
		}

		public Criteria andFechafinpuNotBetween(String value1, String value2) {
			addCriterion("fechaFinPu not between", value1, value2, "fechafinpu");
			return (Criteria) this;
		}

		public Criteria andFechainicioreIsNull() {
			addCriterion("fechaInicioRe is null");
			return (Criteria) this;
		}

		public Criteria andFechainicioreIsNotNull() {
			addCriterion("fechaInicioRe is not null");
			return (Criteria) this;
		}

		public Criteria andFechainicioreEqualTo(String value) {
			addCriterion("fechaInicioRe =", value, "fechainiciore");
			return (Criteria) this;
		}

		public Criteria andFechainicioreNotEqualTo(String value) {
			addCriterion("fechaInicioRe <>", value, "fechainiciore");
			return (Criteria) this;
		}

		public Criteria andFechainicioreGreaterThan(String value) {
			addCriterion("fechaInicioRe >", value, "fechainiciore");
			return (Criteria) this;
		}

		public Criteria andFechainicioreGreaterThanOrEqualTo(String value) {
			addCriterion("fechaInicioRe >=", value, "fechainiciore");
			return (Criteria) this;
		}

		public Criteria andFechainicioreLessThan(String value) {
			addCriterion("fechaInicioRe <", value, "fechainiciore");
			return (Criteria) this;
		}

		public Criteria andFechainicioreLessThanOrEqualTo(String value) {
			addCriterion("fechaInicioRe <=", value, "fechainiciore");
			return (Criteria) this;
		}

		public Criteria andFechainicioreIn(List<String> values) {
			addCriterion("fechaInicioRe in", values, "fechainiciore");
			return (Criteria) this;
		}

		public Criteria andFechainicioreNotIn(List<String> values) {
			addCriterion("fechaInicioRe not in", values, "fechainiciore");
			return (Criteria) this;
		}

		public Criteria andFechainicioreBetween(String value1, String value2) {
			addCriterion("fechaInicioRe between", value1, value2,
					"fechainiciore");
			return (Criteria) this;
		}

		public Criteria andFechainicioreNotBetween(String value1, String value2) {
			addCriterion("fechaInicioRe not between", value1, value2,
					"fechainiciore");
			return (Criteria) this;
		}

		public Criteria andFechafinreIsNull() {
			addCriterion("fechaFinRe is null");
			return (Criteria) this;
		}

		public Criteria andFechafinreIsNotNull() {
			addCriterion("fechaFinRe is not null");
			return (Criteria) this;
		}

		public Criteria andFechafinreEqualTo(String value) {
			addCriterion("fechaFinRe =", value, "fechafinre");
			return (Criteria) this;
		}

		public Criteria andFechafinreNotEqualTo(String value) {
			addCriterion("fechaFinRe <>", value, "fechafinre");
			return (Criteria) this;
		}

		public Criteria andFechafinreGreaterThan(String value) {
			addCriterion("fechaFinRe >", value, "fechafinre");
			return (Criteria) this;
		}

		public Criteria andFechafinreGreaterThanOrEqualTo(String value) {
			addCriterion("fechaFinRe >=", value, "fechafinre");
			return (Criteria) this;
		}

		public Criteria andFechafinreLessThan(String value) {
			addCriterion("fechaFinRe <", value, "fechafinre");
			return (Criteria) this;
		}

		public Criteria andFechafinreLessThanOrEqualTo(String value) {
			addCriterion("fechaFinRe <=", value, "fechafinre");
			return (Criteria) this;
		}

		public Criteria andFechafinreIn(List<String> values) {
			addCriterion("fechaFinRe in", values, "fechafinre");
			return (Criteria) this;
		}

		public Criteria andFechafinreNotIn(List<String> values) {
			addCriterion("fechaFinRe not in", values, "fechafinre");
			return (Criteria) this;
		}

		public Criteria andFechafinreBetween(String value1, String value2) {
			addCriterion("fechaFinRe between", value1, value2, "fechafinre");
			return (Criteria) this;
		}

		public Criteria andFechafinreNotBetween(String value1, String value2) {
			addCriterion("fechaFinRe not between", value1, value2, "fechafinre");
			return (Criteria) this;
		}

		public Criteria andDesIsNull() {
			addCriterion("des is null");
			return (Criteria) this;
		}

		public Criteria andDesIsNotNull() {
			addCriterion("des is not null");
			return (Criteria) this;
		}

		public Criteria andDesEqualTo(String value) {
			addCriterion("des =", value, "des");
			return (Criteria) this;
		}

		public Criteria andDesNotEqualTo(String value) {
			addCriterion("des <>", value, "des");
			return (Criteria) this;
		}

		public Criteria andDesGreaterThan(String value) {
			addCriterion("des >", value, "des");
			return (Criteria) this;
		}

		public Criteria andDesGreaterThanOrEqualTo(String value) {
			addCriterion("des >=", value, "des");
			return (Criteria) this;
		}

		public Criteria andDesLessThan(String value) {
			addCriterion("des <", value, "des");
			return (Criteria) this;
		}

		public Criteria andDesLessThanOrEqualTo(String value) {
			addCriterion("des <=", value, "des");
			return (Criteria) this;
		}

		public Criteria andDesLike(String value) {
			addCriterion("des like", value, "des");
			return (Criteria) this;
		}

		public Criteria andDesNotLike(String value) {
			addCriterion("des not like", value, "des");
			return (Criteria) this;
		}

		public Criteria andDesIn(List<String> values) {
			addCriterion("des in", values, "des");
			return (Criteria) this;
		}

		public Criteria andDesNotIn(List<String> values) {
			addCriterion("des not in", values, "des");
			return (Criteria) this;
		}

		public Criteria andDesBetween(String value1, String value2) {
			addCriterion("des between", value1, value2, "des");
			return (Criteria) this;
		}

		public Criteria andDesNotBetween(String value1, String value2) {
			addCriterion("des not between", value1, value2, "des");
			return (Criteria) this;
		}

		public Criteria andActivoIsNull() {
			addCriterion("activo is null");
			return (Criteria) this;
		}

		public Criteria andActivoIsNotNull() {
			addCriterion("activo is not null");
			return (Criteria) this;
		}

		public Criteria andActivoEqualTo(Boolean value) {
			addCriterion("activo =", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoNotEqualTo(Boolean value) {
			addCriterion("activo <>", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoGreaterThan(Boolean value) {
			addCriterion("activo >", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoGreaterThanOrEqualTo(Boolean value) {
			addCriterion("activo >=", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoLessThan(Boolean value) {
			addCriterion("activo <", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoLessThanOrEqualTo(Boolean value) {
			addCriterion("activo <=", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoIn(List<Boolean> values) {
			addCriterion("activo in", values, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoNotIn(List<Boolean> values) {
			addCriterion("activo not in", values, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoBetween(Boolean value1, Boolean value2) {
			addCriterion("activo between", value1, value2, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoNotBetween(Boolean value1, Boolean value2) {
			addCriterion("activo not between", value1, value2, "activo");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table atarea
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table atarea
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}