package com.pro.proyectospro.configuracion.domain;

import java.util.ArrayList;
import java.util.List;

public class DatospersonaExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table datospersona
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table datospersona
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table datospersona
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table datospersona
	 * @mbggenerated
	 */
	public DatospersonaExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table datospersona
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table datospersona
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table datospersona
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table datospersona
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table datospersona
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table datospersona
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table datospersona
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table datospersona
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table datospersona
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table datospersona
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table datospersona
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCodigoIsNull() {
			addCriterion("codigo is null");
			return (Criteria) this;
		}

		public Criteria andCodigoIsNotNull() {
			addCriterion("codigo is not null");
			return (Criteria) this;
		}

		public Criteria andCodigoEqualTo(Integer value) {
			addCriterion("codigo =", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoNotEqualTo(Integer value) {
			addCriterion("codigo <>", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoGreaterThan(Integer value) {
			addCriterion("codigo >", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoGreaterThanOrEqualTo(Integer value) {
			addCriterion("codigo >=", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoLessThan(Integer value) {
			addCriterion("codigo <", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoLessThanOrEqualTo(Integer value) {
			addCriterion("codigo <=", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoIn(List<Integer> values) {
			addCriterion("codigo in", values, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoNotIn(List<Integer> values) {
			addCriterion("codigo not in", values, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoBetween(Integer value1, Integer value2) {
			addCriterion("codigo between", value1, value2, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoNotBetween(Integer value1, Integer value2) {
			addCriterion("codigo not between", value1, value2, "codigo");
			return (Criteria) this;
		}

		public Criteria andNombreIsNull() {
			addCriterion("nombre is null");
			return (Criteria) this;
		}

		public Criteria andNombreIsNotNull() {
			addCriterion("nombre is not null");
			return (Criteria) this;
		}

		public Criteria andNombreEqualTo(String value) {
			addCriterion("nombre =", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotEqualTo(String value) {
			addCriterion("nombre <>", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreGreaterThan(String value) {
			addCriterion("nombre >", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreGreaterThanOrEqualTo(String value) {
			addCriterion("nombre >=", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreLessThan(String value) {
			addCriterion("nombre <", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreLessThanOrEqualTo(String value) {
			addCriterion("nombre <=", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreLike(String value) {
			addCriterion("nombre like", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotLike(String value) {
			addCriterion("nombre not like", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreIn(List<String> values) {
			addCriterion("nombre in", values, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotIn(List<String> values) {
			addCriterion("nombre not in", values, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreBetween(String value1, String value2) {
			addCriterion("nombre between", value1, value2, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotBetween(String value1, String value2) {
			addCriterion("nombre not between", value1, value2, "nombre");
			return (Criteria) this;
		}

		public Criteria andApellidoIsNull() {
			addCriterion("apellido is null");
			return (Criteria) this;
		}

		public Criteria andApellidoIsNotNull() {
			addCriterion("apellido is not null");
			return (Criteria) this;
		}

		public Criteria andApellidoEqualTo(String value) {
			addCriterion("apellido =", value, "apellido");
			return (Criteria) this;
		}

		public Criteria andApellidoNotEqualTo(String value) {
			addCriterion("apellido <>", value, "apellido");
			return (Criteria) this;
		}

		public Criteria andApellidoGreaterThan(String value) {
			addCriterion("apellido >", value, "apellido");
			return (Criteria) this;
		}

		public Criteria andApellidoGreaterThanOrEqualTo(String value) {
			addCriterion("apellido >=", value, "apellido");
			return (Criteria) this;
		}

		public Criteria andApellidoLessThan(String value) {
			addCriterion("apellido <", value, "apellido");
			return (Criteria) this;
		}

		public Criteria andApellidoLessThanOrEqualTo(String value) {
			addCriterion("apellido <=", value, "apellido");
			return (Criteria) this;
		}

		public Criteria andApellidoLike(String value) {
			addCriterion("apellido like", value, "apellido");
			return (Criteria) this;
		}

		public Criteria andApellidoNotLike(String value) {
			addCriterion("apellido not like", value, "apellido");
			return (Criteria) this;
		}

		public Criteria andApellidoIn(List<String> values) {
			addCriterion("apellido in", values, "apellido");
			return (Criteria) this;
		}

		public Criteria andApellidoNotIn(List<String> values) {
			addCriterion("apellido not in", values, "apellido");
			return (Criteria) this;
		}

		public Criteria andApellidoBetween(String value1, String value2) {
			addCriterion("apellido between", value1, value2, "apellido");
			return (Criteria) this;
		}

		public Criteria andApellidoNotBetween(String value1, String value2) {
			addCriterion("apellido not between", value1, value2, "apellido");
			return (Criteria) this;
		}

		public Criteria andCorreoIsNull() {
			addCriterion("correo is null");
			return (Criteria) this;
		}

		public Criteria andCorreoIsNotNull() {
			addCriterion("correo is not null");
			return (Criteria) this;
		}

		public Criteria andCorreoEqualTo(String value) {
			addCriterion("correo =", value, "correo");
			return (Criteria) this;
		}

		public Criteria andCorreoNotEqualTo(String value) {
			addCriterion("correo <>", value, "correo");
			return (Criteria) this;
		}

		public Criteria andCorreoGreaterThan(String value) {
			addCriterion("correo >", value, "correo");
			return (Criteria) this;
		}

		public Criteria andCorreoGreaterThanOrEqualTo(String value) {
			addCriterion("correo >=", value, "correo");
			return (Criteria) this;
		}

		public Criteria andCorreoLessThan(String value) {
			addCriterion("correo <", value, "correo");
			return (Criteria) this;
		}

		public Criteria andCorreoLessThanOrEqualTo(String value) {
			addCriterion("correo <=", value, "correo");
			return (Criteria) this;
		}

		public Criteria andCorreoLike(String value) {
			addCriterion("correo like", value, "correo");
			return (Criteria) this;
		}

		public Criteria andCorreoNotLike(String value) {
			addCriterion("correo not like", value, "correo");
			return (Criteria) this;
		}

		public Criteria andCorreoIn(List<String> values) {
			addCriterion("correo in", values, "correo");
			return (Criteria) this;
		}

		public Criteria andCorreoNotIn(List<String> values) {
			addCriterion("correo not in", values, "correo");
			return (Criteria) this;
		}

		public Criteria andCorreoBetween(String value1, String value2) {
			addCriterion("correo between", value1, value2, "correo");
			return (Criteria) this;
		}

		public Criteria andCorreoNotBetween(String value1, String value2) {
			addCriterion("correo not between", value1, value2, "correo");
			return (Criteria) this;
		}

		public Criteria andDireccionIsNull() {
			addCriterion("direccion is null");
			return (Criteria) this;
		}

		public Criteria andDireccionIsNotNull() {
			addCriterion("direccion is not null");
			return (Criteria) this;
		}

		public Criteria andDireccionEqualTo(String value) {
			addCriterion("direccion =", value, "direccion");
			return (Criteria) this;
		}

		public Criteria andDireccionNotEqualTo(String value) {
			addCriterion("direccion <>", value, "direccion");
			return (Criteria) this;
		}

		public Criteria andDireccionGreaterThan(String value) {
			addCriterion("direccion >", value, "direccion");
			return (Criteria) this;
		}

		public Criteria andDireccionGreaterThanOrEqualTo(String value) {
			addCriterion("direccion >=", value, "direccion");
			return (Criteria) this;
		}

		public Criteria andDireccionLessThan(String value) {
			addCriterion("direccion <", value, "direccion");
			return (Criteria) this;
		}

		public Criteria andDireccionLessThanOrEqualTo(String value) {
			addCriterion("direccion <=", value, "direccion");
			return (Criteria) this;
		}

		public Criteria andDireccionLike(String value) {
			addCriterion("direccion like", value, "direccion");
			return (Criteria) this;
		}

		public Criteria andDireccionNotLike(String value) {
			addCriterion("direccion not like", value, "direccion");
			return (Criteria) this;
		}

		public Criteria andDireccionIn(List<String> values) {
			addCriterion("direccion in", values, "direccion");
			return (Criteria) this;
		}

		public Criteria andDireccionNotIn(List<String> values) {
			addCriterion("direccion not in", values, "direccion");
			return (Criteria) this;
		}

		public Criteria andDireccionBetween(String value1, String value2) {
			addCriterion("direccion between", value1, value2, "direccion");
			return (Criteria) this;
		}

		public Criteria andDireccionNotBetween(String value1, String value2) {
			addCriterion("direccion not between", value1, value2, "direccion");
			return (Criteria) this;
		}

		public Criteria andTelefonoIsNull() {
			addCriterion("telefono is null");
			return (Criteria) this;
		}

		public Criteria andTelefonoIsNotNull() {
			addCriterion("telefono is not null");
			return (Criteria) this;
		}

		public Criteria andTelefonoEqualTo(String value) {
			addCriterion("telefono =", value, "telefono");
			return (Criteria) this;
		}

		public Criteria andTelefonoNotEqualTo(String value) {
			addCriterion("telefono <>", value, "telefono");
			return (Criteria) this;
		}

		public Criteria andTelefonoGreaterThan(String value) {
			addCriterion("telefono >", value, "telefono");
			return (Criteria) this;
		}

		public Criteria andTelefonoGreaterThanOrEqualTo(String value) {
			addCriterion("telefono >=", value, "telefono");
			return (Criteria) this;
		}

		public Criteria andTelefonoLessThan(String value) {
			addCriterion("telefono <", value, "telefono");
			return (Criteria) this;
		}

		public Criteria andTelefonoLessThanOrEqualTo(String value) {
			addCriterion("telefono <=", value, "telefono");
			return (Criteria) this;
		}

		public Criteria andTelefonoLike(String value) {
			addCriterion("telefono like", value, "telefono");
			return (Criteria) this;
		}

		public Criteria andTelefonoNotLike(String value) {
			addCriterion("telefono not like", value, "telefono");
			return (Criteria) this;
		}

		public Criteria andTelefonoIn(List<String> values) {
			addCriterion("telefono in", values, "telefono");
			return (Criteria) this;
		}

		public Criteria andTelefonoNotIn(List<String> values) {
			addCriterion("telefono not in", values, "telefono");
			return (Criteria) this;
		}

		public Criteria andTelefonoBetween(String value1, String value2) {
			addCriterion("telefono between", value1, value2, "telefono");
			return (Criteria) this;
		}

		public Criteria andTelefonoNotBetween(String value1, String value2) {
			addCriterion("telefono not between", value1, value2, "telefono");
			return (Criteria) this;
		}

		public Criteria andFechanacIsNull() {
			addCriterion("fechaNac is null");
			return (Criteria) this;
		}

		public Criteria andFechanacIsNotNull() {
			addCriterion("fechaNac is not null");
			return (Criteria) this;
		}

		public Criteria andFechanacEqualTo(String value) {
			addCriterion("fechaNac =", value, "fechanac");
			return (Criteria) this;
		}

		public Criteria andFechanacNotEqualTo(String value) {
			addCriterion("fechaNac <>", value, "fechanac");
			return (Criteria) this;
		}

		public Criteria andFechanacGreaterThan(String value) {
			addCriterion("fechaNac >", value, "fechanac");
			return (Criteria) this;
		}

		public Criteria andFechanacGreaterThanOrEqualTo(String value) {
			addCriterion("fechaNac >=", value, "fechanac");
			return (Criteria) this;
		}

		public Criteria andFechanacLessThan(String value) {
			addCriterion("fechaNac <", value, "fechanac");
			return (Criteria) this;
		}

		public Criteria andFechanacLessThanOrEqualTo(String value) {
			addCriterion("fechaNac <=", value, "fechanac");
			return (Criteria) this;
		}

		public Criteria andFechanacIn(List<String> values) {
			addCriterion("fechaNac in", values, "fechanac");
			return (Criteria) this;
		}

		public Criteria andFechanacNotIn(List<String> values) {
			addCriterion("fechaNac not in", values, "fechanac");
			return (Criteria) this;
		}

		public Criteria andFechanacBetween(String value1, String value2) {
			addCriterion("fechaNac between", value1, value2, "fechanac");
			return (Criteria) this;
		}

		public Criteria andFechanacNotBetween(String value1, String value2) {
			addCriterion("fechaNac not between", value1, value2, "fechanac");
			return (Criteria) this;
		}

		public Criteria andDniIsNull() {
			addCriterion("dni is null");
			return (Criteria) this;
		}

		public Criteria andDniIsNotNull() {
			addCriterion("dni is not null");
			return (Criteria) this;
		}

		public Criteria andDniEqualTo(String value) {
			addCriterion("dni =", value, "dni");
			return (Criteria) this;
		}

		public Criteria andDniNotEqualTo(String value) {
			addCriterion("dni <>", value, "dni");
			return (Criteria) this;
		}

		public Criteria andDniGreaterThan(String value) {
			addCriterion("dni >", value, "dni");
			return (Criteria) this;
		}

		public Criteria andDniGreaterThanOrEqualTo(String value) {
			addCriterion("dni >=", value, "dni");
			return (Criteria) this;
		}

		public Criteria andDniLessThan(String value) {
			addCriterion("dni <", value, "dni");
			return (Criteria) this;
		}

		public Criteria andDniLessThanOrEqualTo(String value) {
			addCriterion("dni <=", value, "dni");
			return (Criteria) this;
		}

		public Criteria andDniLike(String value) {
			addCriterion("dni like", value, "dni");
			return (Criteria) this;
		}

		public Criteria andDniNotLike(String value) {
			addCriterion("dni not like", value, "dni");
			return (Criteria) this;
		}

		public Criteria andDniIn(List<String> values) {
			addCriterion("dni in", values, "dni");
			return (Criteria) this;
		}

		public Criteria andDniNotIn(List<String> values) {
			addCriterion("dni not in", values, "dni");
			return (Criteria) this;
		}

		public Criteria andDniBetween(String value1, String value2) {
			addCriterion("dni between", value1, value2, "dni");
			return (Criteria) this;
		}

		public Criteria andDniNotBetween(String value1, String value2) {
			addCriterion("dni not between", value1, value2, "dni");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table datospersona
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table datospersona
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}