package com.pro.proyectospro.configuracion.domain;

public class Datospersona {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column datospersona.codigo
	 * @mbggenerated
	 */
	private Integer codigo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column datospersona.nombre
	 * @mbggenerated
	 */
	private String nombre;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column datospersona.apellido
	 * @mbggenerated
	 */
	private String apellido;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column datospersona.correo
	 * @mbggenerated
	 */
	private String correo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column datospersona.direccion
	 * @mbggenerated
	 */
	private String direccion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column datospersona.telefono
	 * @mbggenerated
	 */
	private String telefono;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column datospersona.fechaNac
	 * @mbggenerated
	 */
	private String fechanac;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column datospersona.dni
	 * @mbggenerated
	 */
	private String dni;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column datospersona.codigo
	 * @return  the value of datospersona.codigo
	 * @mbggenerated
	 */
	public Integer getCodigo() {
		return codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column datospersona.codigo
	 * @param codigo  the value for datospersona.codigo
	 * @mbggenerated
	 */
	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column datospersona.nombre
	 * @return  the value of datospersona.nombre
	 * @mbggenerated
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column datospersona.nombre
	 * @param nombre  the value for datospersona.nombre
	 * @mbggenerated
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column datospersona.apellido
	 * @return  the value of datospersona.apellido
	 * @mbggenerated
	 */
	public String getApellido() {
		return apellido;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column datospersona.apellido
	 * @param apellido  the value for datospersona.apellido
	 * @mbggenerated
	 */
	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column datospersona.correo
	 * @return  the value of datospersona.correo
	 * @mbggenerated
	 */
	public String getCorreo() {
		return correo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column datospersona.correo
	 * @param correo  the value for datospersona.correo
	 * @mbggenerated
	 */
	public void setCorreo(String correo) {
		this.correo = correo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column datospersona.direccion
	 * @return  the value of datospersona.direccion
	 * @mbggenerated
	 */
	public String getDireccion() {
		return direccion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column datospersona.direccion
	 * @param direccion  the value for datospersona.direccion
	 * @mbggenerated
	 */
	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column datospersona.telefono
	 * @return  the value of datospersona.telefono
	 * @mbggenerated
	 */
	public String getTelefono() {
		return telefono;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column datospersona.telefono
	 * @param telefono  the value for datospersona.telefono
	 * @mbggenerated
	 */
	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column datospersona.fechaNac
	 * @return  the value of datospersona.fechaNac
	 * @mbggenerated
	 */
	public String getFechanac() {
		return fechanac;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column datospersona.fechaNac
	 * @param fechanac  the value for datospersona.fechaNac
	 * @mbggenerated
	 */
	public void setFechanac(String fechanac) {
		this.fechanac = fechanac;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column datospersona.dni
	 * @return  the value of datospersona.dni
	 * @mbggenerated
	 */
	public String getDni() {
		return dni;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column datospersona.dni
	 * @param dni  the value for datospersona.dni
	 * @mbggenerated
	 */
	public void setDni(String dni) {
		this.dni = dni;
	}
}