package com.pro.proyectospro.configuracion.domain;

public class Fase {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fase.codigo
	 * @mbggenerated
	 */
	private Integer codigo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fase.des
	 * @mbggenerated
	 */
	private String des;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fase.orden
	 * @mbggenerated
	 */
	private Integer orden;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fase.activo
	 * @mbggenerated
	 */
	private Boolean activo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fase.codigo
	 * @return  the value of fase.codigo
	 * @mbggenerated
	 */
	public Integer getCodigo() {
		return codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fase.codigo
	 * @param codigo  the value for fase.codigo
	 * @mbggenerated
	 */
	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fase.des
	 * @return  the value of fase.des
	 * @mbggenerated
	 */
	public String getDes() {
		return des;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fase.des
	 * @param des  the value for fase.des
	 * @mbggenerated
	 */
	public void setDes(String des) {
		this.des = des;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fase.orden
	 * @return  the value of fase.orden
	 * @mbggenerated
	 */
	public Integer getOrden() {
		return orden;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fase.orden
	 * @param orden  the value for fase.orden
	 * @mbggenerated
	 */
	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fase.activo
	 * @return  the value of fase.activo
	 * @mbggenerated
	 */
	public Boolean getActivo() {
		return activo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fase.activo
	 * @param activo  the value for fase.activo
	 * @mbggenerated
	 */
	public void setActivo(Boolean activo) {
		this.activo = activo;
	}
}