package com.pro.proyectospro.configuracion.domain;

public class Gerente {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gerente.codigo
	 * @mbggenerated
	 */
	private Integer codigo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gerente.codUsuario
	 * @mbggenerated
	 */
	private Integer codusuario;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gerente.codDatosPersona
	 * @mbggenerated
	 */
	private Integer coddatospersona;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gerente.activo
	 * @mbggenerated
	 */
	private Boolean activo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gerente.codigo
	 * @return  the value of gerente.codigo
	 * @mbggenerated
	 */
	public Integer getCodigo() {
		return codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gerente.codigo
	 * @param codigo  the value for gerente.codigo
	 * @mbggenerated
	 */
	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gerente.codUsuario
	 * @return  the value of gerente.codUsuario
	 * @mbggenerated
	 */
	public Integer getCodusuario() {
		return codusuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gerente.codUsuario
	 * @param codusuario  the value for gerente.codUsuario
	 * @mbggenerated
	 */
	public void setCodusuario(Integer codusuario) {
		this.codusuario = codusuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gerente.codDatosPersona
	 * @return  the value of gerente.codDatosPersona
	 * @mbggenerated
	 */
	public Integer getCoddatospersona() {
		return coddatospersona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gerente.codDatosPersona
	 * @param coddatospersona  the value for gerente.codDatosPersona
	 * @mbggenerated
	 */
	public void setCoddatospersona(Integer coddatospersona) {
		this.coddatospersona = coddatospersona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gerente.activo
	 * @return  the value of gerente.activo
	 * @mbggenerated
	 */
	public Boolean getActivo() {
		return activo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gerente.activo
	 * @param activo  the value for gerente.activo
	 * @mbggenerated
	 */
	public void setActivo(Boolean activo) {
		this.activo = activo;
	}
}