package com.pro.proyectospro.configuracion.domain;

public class Interesado {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interesado.codigo
	 * @mbggenerated
	 */
	private Integer codigo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interesado.empresa
	 * @mbggenerated
	 */
	private String empresa;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interesado.direccionE
	 * @mbggenerated
	 */
	private String direccione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interesado.telefonoE
	 * @mbggenerated
	 */
	private String telefonoe;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interesado.paginaWeb
	 * @mbggenerated
	 */
	private String paginaweb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interesado.codDatosPersona
	 * @mbggenerated
	 */
	private Integer coddatospersona;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interesado.codProyecto
	 * @mbggenerated
	 */
	private Integer codproyecto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interesado.sponsor
	 * @mbggenerated
	 */
	private Boolean sponsor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column interesado.activo
	 * @mbggenerated
	 */
	private Boolean activo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interesado.codigo
	 * @return  the value of interesado.codigo
	 * @mbggenerated
	 */
	public Integer getCodigo() {
		return codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interesado.codigo
	 * @param codigo  the value for interesado.codigo
	 * @mbggenerated
	 */
	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interesado.empresa
	 * @return  the value of interesado.empresa
	 * @mbggenerated
	 */
	public String getEmpresa() {
		return empresa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interesado.empresa
	 * @param empresa  the value for interesado.empresa
	 * @mbggenerated
	 */
	public void setEmpresa(String empresa) {
		this.empresa = empresa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interesado.direccionE
	 * @return  the value of interesado.direccionE
	 * @mbggenerated
	 */
	public String getDireccione() {
		return direccione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interesado.direccionE
	 * @param direccione  the value for interesado.direccionE
	 * @mbggenerated
	 */
	public void setDireccione(String direccione) {
		this.direccione = direccione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interesado.telefonoE
	 * @return  the value of interesado.telefonoE
	 * @mbggenerated
	 */
	public String getTelefonoe() {
		return telefonoe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interesado.telefonoE
	 * @param telefonoe  the value for interesado.telefonoE
	 * @mbggenerated
	 */
	public void setTelefonoe(String telefonoe) {
		this.telefonoe = telefonoe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interesado.paginaWeb
	 * @return  the value of interesado.paginaWeb
	 * @mbggenerated
	 */
	public String getPaginaweb() {
		return paginaweb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interesado.paginaWeb
	 * @param paginaweb  the value for interesado.paginaWeb
	 * @mbggenerated
	 */
	public void setPaginaweb(String paginaweb) {
		this.paginaweb = paginaweb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interesado.codDatosPersona
	 * @return  the value of interesado.codDatosPersona
	 * @mbggenerated
	 */
	public Integer getCoddatospersona() {
		return coddatospersona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interesado.codDatosPersona
	 * @param coddatospersona  the value for interesado.codDatosPersona
	 * @mbggenerated
	 */
	public void setCoddatospersona(Integer coddatospersona) {
		this.coddatospersona = coddatospersona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interesado.codProyecto
	 * @return  the value of interesado.codProyecto
	 * @mbggenerated
	 */
	public Integer getCodproyecto() {
		return codproyecto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interesado.codProyecto
	 * @param codproyecto  the value for interesado.codProyecto
	 * @mbggenerated
	 */
	public void setCodproyecto(Integer codproyecto) {
		this.codproyecto = codproyecto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interesado.sponsor
	 * @return  the value of interesado.sponsor
	 * @mbggenerated
	 */
	public Boolean getSponsor() {
		return sponsor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interesado.sponsor
	 * @param sponsor  the value for interesado.sponsor
	 * @mbggenerated
	 */
	public void setSponsor(Boolean sponsor) {
		this.sponsor = sponsor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column interesado.activo
	 * @return  the value of interesado.activo
	 * @mbggenerated
	 */
	public Boolean getActivo() {
		return activo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column interesado.activo
	 * @param activo  the value for interesado.activo
	 * @mbggenerated
	 */
	public void setActivo(Boolean activo) {
		this.activo = activo;
	}
}