package com.pro.proyectospro.configuracion.domain;

import java.util.ArrayList;
import java.util.List;

public class PdocumentoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pdocumento
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pdocumento
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pdocumento
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdocumento
	 * @mbggenerated
	 */
	public PdocumentoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdocumento
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdocumento
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdocumento
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdocumento
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdocumento
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdocumento
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdocumento
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdocumento
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdocumento
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdocumento
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table pdocumento
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCodigoIsNull() {
			addCriterion("codigo is null");
			return (Criteria) this;
		}

		public Criteria andCodigoIsNotNull() {
			addCriterion("codigo is not null");
			return (Criteria) this;
		}

		public Criteria andCodigoEqualTo(Integer value) {
			addCriterion("codigo =", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoNotEqualTo(Integer value) {
			addCriterion("codigo <>", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoGreaterThan(Integer value) {
			addCriterion("codigo >", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoGreaterThanOrEqualTo(Integer value) {
			addCriterion("codigo >=", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoLessThan(Integer value) {
			addCriterion("codigo <", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoLessThanOrEqualTo(Integer value) {
			addCriterion("codigo <=", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoIn(List<Integer> values) {
			addCriterion("codigo in", values, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoNotIn(List<Integer> values) {
			addCriterion("codigo not in", values, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoBetween(Integer value1, Integer value2) {
			addCriterion("codigo between", value1, value2, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoNotBetween(Integer value1, Integer value2) {
			addCriterion("codigo not between", value1, value2, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodpfaseIsNull() {
			addCriterion("codPFase is null");
			return (Criteria) this;
		}

		public Criteria andCodpfaseIsNotNull() {
			addCriterion("codPFase is not null");
			return (Criteria) this;
		}

		public Criteria andCodpfaseEqualTo(Integer value) {
			addCriterion("codPFase =", value, "codpfase");
			return (Criteria) this;
		}

		public Criteria andCodpfaseNotEqualTo(Integer value) {
			addCriterion("codPFase <>", value, "codpfase");
			return (Criteria) this;
		}

		public Criteria andCodpfaseGreaterThan(Integer value) {
			addCriterion("codPFase >", value, "codpfase");
			return (Criteria) this;
		}

		public Criteria andCodpfaseGreaterThanOrEqualTo(Integer value) {
			addCriterion("codPFase >=", value, "codpfase");
			return (Criteria) this;
		}

		public Criteria andCodpfaseLessThan(Integer value) {
			addCriterion("codPFase <", value, "codpfase");
			return (Criteria) this;
		}

		public Criteria andCodpfaseLessThanOrEqualTo(Integer value) {
			addCriterion("codPFase <=", value, "codpfase");
			return (Criteria) this;
		}

		public Criteria andCodpfaseIn(List<Integer> values) {
			addCriterion("codPFase in", values, "codpfase");
			return (Criteria) this;
		}

		public Criteria andCodpfaseNotIn(List<Integer> values) {
			addCriterion("codPFase not in", values, "codpfase");
			return (Criteria) this;
		}

		public Criteria andCodpfaseBetween(Integer value1, Integer value2) {
			addCriterion("codPFase between", value1, value2, "codpfase");
			return (Criteria) this;
		}

		public Criteria andCodpfaseNotBetween(Integer value1, Integer value2) {
			addCriterion("codPFase not between", value1, value2, "codpfase");
			return (Criteria) this;
		}

		public Criteria andCoddocumento1IsNull() {
			addCriterion("codDocumento1 is null");
			return (Criteria) this;
		}

		public Criteria andCoddocumento1IsNotNull() {
			addCriterion("codDocumento1 is not null");
			return (Criteria) this;
		}

		public Criteria andCoddocumento1EqualTo(Integer value) {
			addCriterion("codDocumento1 =", value, "coddocumento1");
			return (Criteria) this;
		}

		public Criteria andCoddocumento1NotEqualTo(Integer value) {
			addCriterion("codDocumento1 <>", value, "coddocumento1");
			return (Criteria) this;
		}

		public Criteria andCoddocumento1GreaterThan(Integer value) {
			addCriterion("codDocumento1 >", value, "coddocumento1");
			return (Criteria) this;
		}

		public Criteria andCoddocumento1GreaterThanOrEqualTo(Integer value) {
			addCriterion("codDocumento1 >=", value, "coddocumento1");
			return (Criteria) this;
		}

		public Criteria andCoddocumento1LessThan(Integer value) {
			addCriterion("codDocumento1 <", value, "coddocumento1");
			return (Criteria) this;
		}

		public Criteria andCoddocumento1LessThanOrEqualTo(Integer value) {
			addCriterion("codDocumento1 <=", value, "coddocumento1");
			return (Criteria) this;
		}

		public Criteria andCoddocumento1In(List<Integer> values) {
			addCriterion("codDocumento1 in", values, "coddocumento1");
			return (Criteria) this;
		}

		public Criteria andCoddocumento1NotIn(List<Integer> values) {
			addCriterion("codDocumento1 not in", values, "coddocumento1");
			return (Criteria) this;
		}

		public Criteria andCoddocumento1Between(Integer value1, Integer value2) {
			addCriterion("codDocumento1 between", value1, value2,
					"coddocumento1");
			return (Criteria) this;
		}

		public Criteria andCoddocumento1NotBetween(Integer value1,
				Integer value2) {
			addCriterion("codDocumento1 not between", value1, value2,
					"coddocumento1");
			return (Criteria) this;
		}

		public Criteria andFechasubidoIsNull() {
			addCriterion("fechaSubido is null");
			return (Criteria) this;
		}

		public Criteria andFechasubidoIsNotNull() {
			addCriterion("fechaSubido is not null");
			return (Criteria) this;
		}

		public Criteria andFechasubidoEqualTo(String value) {
			addCriterion("fechaSubido =", value, "fechasubido");
			return (Criteria) this;
		}

		public Criteria andFechasubidoNotEqualTo(String value) {
			addCriterion("fechaSubido <>", value, "fechasubido");
			return (Criteria) this;
		}

		public Criteria andFechasubidoGreaterThan(String value) {
			addCriterion("fechaSubido >", value, "fechasubido");
			return (Criteria) this;
		}

		public Criteria andFechasubidoGreaterThanOrEqualTo(String value) {
			addCriterion("fechaSubido >=", value, "fechasubido");
			return (Criteria) this;
		}

		public Criteria andFechasubidoLessThan(String value) {
			addCriterion("fechaSubido <", value, "fechasubido");
			return (Criteria) this;
		}

		public Criteria andFechasubidoLessThanOrEqualTo(String value) {
			addCriterion("fechaSubido <=", value, "fechasubido");
			return (Criteria) this;
		}

		public Criteria andFechasubidoIn(List<String> values) {
			addCriterion("fechaSubido in", values, "fechasubido");
			return (Criteria) this;
		}

		public Criteria andFechasubidoNotIn(List<String> values) {
			addCriterion("fechaSubido not in", values, "fechasubido");
			return (Criteria) this;
		}

		public Criteria andFechasubidoBetween(String value1, String value2) {
			addCriterion("fechaSubido between", value1, value2, "fechasubido");
			return (Criteria) this;
		}

		public Criteria andFechasubidoNotBetween(String value1, String value2) {
			addCriterion("fechaSubido not between", value1, value2,
					"fechasubido");
			return (Criteria) this;
		}

		public Criteria andRutaIsNull() {
			addCriterion("ruta is null");
			return (Criteria) this;
		}

		public Criteria andRutaIsNotNull() {
			addCriterion("ruta is not null");
			return (Criteria) this;
		}

		public Criteria andRutaEqualTo(String value) {
			addCriterion("ruta =", value, "ruta");
			return (Criteria) this;
		}

		public Criteria andRutaNotEqualTo(String value) {
			addCriterion("ruta <>", value, "ruta");
			return (Criteria) this;
		}

		public Criteria andRutaGreaterThan(String value) {
			addCriterion("ruta >", value, "ruta");
			return (Criteria) this;
		}

		public Criteria andRutaGreaterThanOrEqualTo(String value) {
			addCriterion("ruta >=", value, "ruta");
			return (Criteria) this;
		}

		public Criteria andRutaLessThan(String value) {
			addCriterion("ruta <", value, "ruta");
			return (Criteria) this;
		}

		public Criteria andRutaLessThanOrEqualTo(String value) {
			addCriterion("ruta <=", value, "ruta");
			return (Criteria) this;
		}

		public Criteria andRutaLike(String value) {
			addCriterion("ruta like", value, "ruta");
			return (Criteria) this;
		}

		public Criteria andRutaNotLike(String value) {
			addCriterion("ruta not like", value, "ruta");
			return (Criteria) this;
		}

		public Criteria andRutaIn(List<String> values) {
			addCriterion("ruta in", values, "ruta");
			return (Criteria) this;
		}

		public Criteria andRutaNotIn(List<String> values) {
			addCriterion("ruta not in", values, "ruta");
			return (Criteria) this;
		}

		public Criteria andRutaBetween(String value1, String value2) {
			addCriterion("ruta between", value1, value2, "ruta");
			return (Criteria) this;
		}

		public Criteria andRutaNotBetween(String value1, String value2) {
			addCriterion("ruta not between", value1, value2, "ruta");
			return (Criteria) this;
		}

		public Criteria andActivoIsNull() {
			addCriterion("activo is null");
			return (Criteria) this;
		}

		public Criteria andActivoIsNotNull() {
			addCriterion("activo is not null");
			return (Criteria) this;
		}

		public Criteria andActivoEqualTo(Boolean value) {
			addCriterion("activo =", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoNotEqualTo(Boolean value) {
			addCriterion("activo <>", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoGreaterThan(Boolean value) {
			addCriterion("activo >", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoGreaterThanOrEqualTo(Boolean value) {
			addCriterion("activo >=", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoLessThan(Boolean value) {
			addCriterion("activo <", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoLessThanOrEqualTo(Boolean value) {
			addCriterion("activo <=", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoIn(List<Boolean> values) {
			addCriterion("activo in", values, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoNotIn(List<Boolean> values) {
			addCriterion("activo not in", values, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoBetween(Boolean value1, Boolean value2) {
			addCriterion("activo between", value1, value2, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoNotBetween(Boolean value1, Boolean value2) {
			addCriterion("activo not between", value1, value2, "activo");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table pdocumento
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pdocumento
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}