package com.pro.proyectospro.configuracion.domain;

public class Pdocumento {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pdocumento.codigo
	 * @mbggenerated
	 */
	private Integer codigo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pdocumento.codPFase
	 * @mbggenerated
	 */
	private Integer codpfase;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pdocumento.codDocumento1
	 * @mbggenerated
	 */
	private Integer coddocumento1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pdocumento.fechaSubido
	 * @mbggenerated
	 */
	private String fechasubido;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pdocumento.ruta
	 * @mbggenerated
	 */
	private String ruta;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pdocumento.activo
	 * @mbggenerated
	 */
	private Boolean activo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pdocumento.codigo
	 * @return  the value of pdocumento.codigo
	 * @mbggenerated
	 */
	public Integer getCodigo() {
		return codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pdocumento.codigo
	 * @param codigo  the value for pdocumento.codigo
	 * @mbggenerated
	 */
	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pdocumento.codPFase
	 * @return  the value of pdocumento.codPFase
	 * @mbggenerated
	 */
	public Integer getCodpfase() {
		return codpfase;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pdocumento.codPFase
	 * @param codpfase  the value for pdocumento.codPFase
	 * @mbggenerated
	 */
	public void setCodpfase(Integer codpfase) {
		this.codpfase = codpfase;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pdocumento.codDocumento1
	 * @return  the value of pdocumento.codDocumento1
	 * @mbggenerated
	 */
	public Integer getCoddocumento1() {
		return coddocumento1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pdocumento.codDocumento1
	 * @param coddocumento1  the value for pdocumento.codDocumento1
	 * @mbggenerated
	 */
	public void setCoddocumento1(Integer coddocumento1) {
		this.coddocumento1 = coddocumento1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pdocumento.fechaSubido
	 * @return  the value of pdocumento.fechaSubido
	 * @mbggenerated
	 */
	public String getFechasubido() {
		return fechasubido;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pdocumento.fechaSubido
	 * @param fechasubido  the value for pdocumento.fechaSubido
	 * @mbggenerated
	 */
	public void setFechasubido(String fechasubido) {
		this.fechasubido = fechasubido;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pdocumento.ruta
	 * @return  the value of pdocumento.ruta
	 * @mbggenerated
	 */
	public String getRuta() {
		return ruta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pdocumento.ruta
	 * @param ruta  the value for pdocumento.ruta
	 * @mbggenerated
	 */
	public void setRuta(String ruta) {
		this.ruta = ruta;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pdocumento.activo
	 * @return  the value of pdocumento.activo
	 * @mbggenerated
	 */
	public Boolean getActivo() {
		return activo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pdocumento.activo
	 * @param activo  the value for pdocumento.activo
	 * @mbggenerated
	 */
	public void setActivo(Boolean activo) {
		this.activo = activo;
	}
}