package com.pro.proyectospro.configuracion.domain;

import java.util.ArrayList;
import java.util.List;

public class PfaseExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pfase
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pfase
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pfase
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfase
	 * @mbggenerated
	 */
	public PfaseExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfase
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfase
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfase
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfase
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfase
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfase
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfase
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfase
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfase
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfase
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table pfase
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCodigoIsNull() {
			addCriterion("codigo is null");
			return (Criteria) this;
		}

		public Criteria andCodigoIsNotNull() {
			addCriterion("codigo is not null");
			return (Criteria) this;
		}

		public Criteria andCodigoEqualTo(Integer value) {
			addCriterion("codigo =", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoNotEqualTo(Integer value) {
			addCriterion("codigo <>", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoGreaterThan(Integer value) {
			addCriterion("codigo >", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoGreaterThanOrEqualTo(Integer value) {
			addCriterion("codigo >=", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoLessThan(Integer value) {
			addCriterion("codigo <", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoLessThanOrEqualTo(Integer value) {
			addCriterion("codigo <=", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoIn(List<Integer> values) {
			addCriterion("codigo in", values, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoNotIn(List<Integer> values) {
			addCriterion("codigo not in", values, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoBetween(Integer value1, Integer value2) {
			addCriterion("codigo between", value1, value2, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoNotBetween(Integer value1, Integer value2) {
			addCriterion("codigo not between", value1, value2, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigofaseIsNull() {
			addCriterion("codigoFase is null");
			return (Criteria) this;
		}

		public Criteria andCodigofaseIsNotNull() {
			addCriterion("codigoFase is not null");
			return (Criteria) this;
		}

		public Criteria andCodigofaseEqualTo(Integer value) {
			addCriterion("codigoFase =", value, "codigofase");
			return (Criteria) this;
		}

		public Criteria andCodigofaseNotEqualTo(Integer value) {
			addCriterion("codigoFase <>", value, "codigofase");
			return (Criteria) this;
		}

		public Criteria andCodigofaseGreaterThan(Integer value) {
			addCriterion("codigoFase >", value, "codigofase");
			return (Criteria) this;
		}

		public Criteria andCodigofaseGreaterThanOrEqualTo(Integer value) {
			addCriterion("codigoFase >=", value, "codigofase");
			return (Criteria) this;
		}

		public Criteria andCodigofaseLessThan(Integer value) {
			addCriterion("codigoFase <", value, "codigofase");
			return (Criteria) this;
		}

		public Criteria andCodigofaseLessThanOrEqualTo(Integer value) {
			addCriterion("codigoFase <=", value, "codigofase");
			return (Criteria) this;
		}

		public Criteria andCodigofaseIn(List<Integer> values) {
			addCriterion("codigoFase in", values, "codigofase");
			return (Criteria) this;
		}

		public Criteria andCodigofaseNotIn(List<Integer> values) {
			addCriterion("codigoFase not in", values, "codigofase");
			return (Criteria) this;
		}

		public Criteria andCodigofaseBetween(Integer value1, Integer value2) {
			addCriterion("codigoFase between", value1, value2, "codigofase");
			return (Criteria) this;
		}

		public Criteria andCodigofaseNotBetween(Integer value1, Integer value2) {
			addCriterion("codigoFase not between", value1, value2, "codigofase");
			return (Criteria) this;
		}

		public Criteria andCodpproyectoIsNull() {
			addCriterion("codPProyecto is null");
			return (Criteria) this;
		}

		public Criteria andCodpproyectoIsNotNull() {
			addCriterion("codPProyecto is not null");
			return (Criteria) this;
		}

		public Criteria andCodpproyectoEqualTo(Integer value) {
			addCriterion("codPProyecto =", value, "codpproyecto");
			return (Criteria) this;
		}

		public Criteria andCodpproyectoNotEqualTo(Integer value) {
			addCriterion("codPProyecto <>", value, "codpproyecto");
			return (Criteria) this;
		}

		public Criteria andCodpproyectoGreaterThan(Integer value) {
			addCriterion("codPProyecto >", value, "codpproyecto");
			return (Criteria) this;
		}

		public Criteria andCodpproyectoGreaterThanOrEqualTo(Integer value) {
			addCriterion("codPProyecto >=", value, "codpproyecto");
			return (Criteria) this;
		}

		public Criteria andCodpproyectoLessThan(Integer value) {
			addCriterion("codPProyecto <", value, "codpproyecto");
			return (Criteria) this;
		}

		public Criteria andCodpproyectoLessThanOrEqualTo(Integer value) {
			addCriterion("codPProyecto <=", value, "codpproyecto");
			return (Criteria) this;
		}

		public Criteria andCodpproyectoIn(List<Integer> values) {
			addCriterion("codPProyecto in", values, "codpproyecto");
			return (Criteria) this;
		}

		public Criteria andCodpproyectoNotIn(List<Integer> values) {
			addCriterion("codPProyecto not in", values, "codpproyecto");
			return (Criteria) this;
		}

		public Criteria andCodpproyectoBetween(Integer value1, Integer value2) {
			addCriterion("codPProyecto between", value1, value2, "codpproyecto");
			return (Criteria) this;
		}

		public Criteria andCodpproyectoNotBetween(Integer value1, Integer value2) {
			addCriterion("codPProyecto not between", value1, value2,
					"codpproyecto");
			return (Criteria) this;
		}

		public Criteria andCodestadoIsNull() {
			addCriterion("codEstado is null");
			return (Criteria) this;
		}

		public Criteria andCodestadoIsNotNull() {
			addCriterion("codEstado is not null");
			return (Criteria) this;
		}

		public Criteria andCodestadoEqualTo(Integer value) {
			addCriterion("codEstado =", value, "codestado");
			return (Criteria) this;
		}

		public Criteria andCodestadoNotEqualTo(Integer value) {
			addCriterion("codEstado <>", value, "codestado");
			return (Criteria) this;
		}

		public Criteria andCodestadoGreaterThan(Integer value) {
			addCriterion("codEstado >", value, "codestado");
			return (Criteria) this;
		}

		public Criteria andCodestadoGreaterThanOrEqualTo(Integer value) {
			addCriterion("codEstado >=", value, "codestado");
			return (Criteria) this;
		}

		public Criteria andCodestadoLessThan(Integer value) {
			addCriterion("codEstado <", value, "codestado");
			return (Criteria) this;
		}

		public Criteria andCodestadoLessThanOrEqualTo(Integer value) {
			addCriterion("codEstado <=", value, "codestado");
			return (Criteria) this;
		}

		public Criteria andCodestadoIn(List<Integer> values) {
			addCriterion("codEstado in", values, "codestado");
			return (Criteria) this;
		}

		public Criteria andCodestadoNotIn(List<Integer> values) {
			addCriterion("codEstado not in", values, "codestado");
			return (Criteria) this;
		}

		public Criteria andCodestadoBetween(Integer value1, Integer value2) {
			addCriterion("codEstado between", value1, value2, "codestado");
			return (Criteria) this;
		}

		public Criteria andCodestadoNotBetween(Integer value1, Integer value2) {
			addCriterion("codEstado not between", value1, value2, "codestado");
			return (Criteria) this;
		}

		public Criteria andActivoIsNull() {
			addCriterion("activo is null");
			return (Criteria) this;
		}

		public Criteria andActivoIsNotNull() {
			addCriterion("activo is not null");
			return (Criteria) this;
		}

		public Criteria andActivoEqualTo(Boolean value) {
			addCriterion("activo =", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoNotEqualTo(Boolean value) {
			addCriterion("activo <>", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoGreaterThan(Boolean value) {
			addCriterion("activo >", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoGreaterThanOrEqualTo(Boolean value) {
			addCriterion("activo >=", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoLessThan(Boolean value) {
			addCriterion("activo <", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoLessThanOrEqualTo(Boolean value) {
			addCriterion("activo <=", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoIn(List<Boolean> values) {
			addCriterion("activo in", values, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoNotIn(List<Boolean> values) {
			addCriterion("activo not in", values, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoBetween(Boolean value1, Boolean value2) {
			addCriterion("activo between", value1, value2, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoNotBetween(Boolean value1, Boolean value2) {
			addCriterion("activo not between", value1, value2, "activo");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table pfase
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pfase
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}