package com.pro.proyectospro.configuracion.domain;

public class Pfase {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pfase.codigo
	 * @mbggenerated
	 */
	private Integer codigo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pfase.codigoFase
	 * @mbggenerated
	 */
	private Integer codigofase;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pfase.codPProyecto
	 * @mbggenerated
	 */
	private Integer codpproyecto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pfase.codEstado
	 * @mbggenerated
	 */
	private Integer codestado;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pfase.activo
	 * @mbggenerated
	 */
	private Boolean activo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pfase.codigo
	 * @return  the value of pfase.codigo
	 * @mbggenerated
	 */
	public Integer getCodigo() {
		return codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pfase.codigo
	 * @param codigo  the value for pfase.codigo
	 * @mbggenerated
	 */
	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pfase.codigoFase
	 * @return  the value of pfase.codigoFase
	 * @mbggenerated
	 */
	public Integer getCodigofase() {
		return codigofase;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pfase.codigoFase
	 * @param codigofase  the value for pfase.codigoFase
	 * @mbggenerated
	 */
	public void setCodigofase(Integer codigofase) {
		this.codigofase = codigofase;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pfase.codPProyecto
	 * @return  the value of pfase.codPProyecto
	 * @mbggenerated
	 */
	public Integer getCodpproyecto() {
		return codpproyecto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pfase.codPProyecto
	 * @param codpproyecto  the value for pfase.codPProyecto
	 * @mbggenerated
	 */
	public void setCodpproyecto(Integer codpproyecto) {
		this.codpproyecto = codpproyecto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pfase.codEstado
	 * @return  the value of pfase.codEstado
	 * @mbggenerated
	 */
	public Integer getCodestado() {
		return codestado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pfase.codEstado
	 * @param codestado  the value for pfase.codEstado
	 * @mbggenerated
	 */
	public void setCodestado(Integer codestado) {
		this.codestado = codestado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pfase.activo
	 * @return  the value of pfase.activo
	 * @mbggenerated
	 */
	public Boolean getActivo() {
		return activo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pfase.activo
	 * @param activo  the value for pfase.activo
	 * @mbggenerated
	 */
	public void setActivo(Boolean activo) {
		this.activo = activo;
	}
}