package com.pro.proyectospro.configuracion.domain;

import java.util.ArrayList;
import java.util.List;

public class PincidenciaExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pincidencia
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pincidencia
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pincidencia
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pincidencia
	 * @mbggenerated
	 */
	public PincidenciaExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pincidencia
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pincidencia
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pincidencia
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pincidencia
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pincidencia
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pincidencia
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pincidencia
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pincidencia
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pincidencia
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pincidencia
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table pincidencia
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCodigoIsNull() {
			addCriterion("codigo is null");
			return (Criteria) this;
		}

		public Criteria andCodigoIsNotNull() {
			addCriterion("codigo is not null");
			return (Criteria) this;
		}

		public Criteria andCodigoEqualTo(Integer value) {
			addCriterion("codigo =", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoNotEqualTo(Integer value) {
			addCriterion("codigo <>", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoGreaterThan(Integer value) {
			addCriterion("codigo >", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoGreaterThanOrEqualTo(Integer value) {
			addCriterion("codigo >=", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoLessThan(Integer value) {
			addCriterion("codigo <", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoLessThanOrEqualTo(Integer value) {
			addCriterion("codigo <=", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoIn(List<Integer> values) {
			addCriterion("codigo in", values, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoNotIn(List<Integer> values) {
			addCriterion("codigo not in", values, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoBetween(Integer value1, Integer value2) {
			addCriterion("codigo between", value1, value2, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoNotBetween(Integer value1, Integer value2) {
			addCriterion("codigo not between", value1, value2, "codigo");
			return (Criteria) this;
		}

		public Criteria andDesIsNull() {
			addCriterion("des is null");
			return (Criteria) this;
		}

		public Criteria andDesIsNotNull() {
			addCriterion("des is not null");
			return (Criteria) this;
		}

		public Criteria andDesEqualTo(String value) {
			addCriterion("des =", value, "des");
			return (Criteria) this;
		}

		public Criteria andDesNotEqualTo(String value) {
			addCriterion("des <>", value, "des");
			return (Criteria) this;
		}

		public Criteria andDesGreaterThan(String value) {
			addCriterion("des >", value, "des");
			return (Criteria) this;
		}

		public Criteria andDesGreaterThanOrEqualTo(String value) {
			addCriterion("des >=", value, "des");
			return (Criteria) this;
		}

		public Criteria andDesLessThan(String value) {
			addCriterion("des <", value, "des");
			return (Criteria) this;
		}

		public Criteria andDesLessThanOrEqualTo(String value) {
			addCriterion("des <=", value, "des");
			return (Criteria) this;
		}

		public Criteria andDesLike(String value) {
			addCriterion("des like", value, "des");
			return (Criteria) this;
		}

		public Criteria andDesNotLike(String value) {
			addCriterion("des not like", value, "des");
			return (Criteria) this;
		}

		public Criteria andDesIn(List<String> values) {
			addCriterion("des in", values, "des");
			return (Criteria) this;
		}

		public Criteria andDesNotIn(List<String> values) {
			addCriterion("des not in", values, "des");
			return (Criteria) this;
		}

		public Criteria andDesBetween(String value1, String value2) {
			addCriterion("des between", value1, value2, "des");
			return (Criteria) this;
		}

		public Criteria andDesNotBetween(String value1, String value2) {
			addCriterion("des not between", value1, value2, "des");
			return (Criteria) this;
		}

		public Criteria andCodurgenciaIsNull() {
			addCriterion("codUrgencia is null");
			return (Criteria) this;
		}

		public Criteria andCodurgenciaIsNotNull() {
			addCriterion("codUrgencia is not null");
			return (Criteria) this;
		}

		public Criteria andCodurgenciaEqualTo(Integer value) {
			addCriterion("codUrgencia =", value, "codurgencia");
			return (Criteria) this;
		}

		public Criteria andCodurgenciaNotEqualTo(Integer value) {
			addCriterion("codUrgencia <>", value, "codurgencia");
			return (Criteria) this;
		}

		public Criteria andCodurgenciaGreaterThan(Integer value) {
			addCriterion("codUrgencia >", value, "codurgencia");
			return (Criteria) this;
		}

		public Criteria andCodurgenciaGreaterThanOrEqualTo(Integer value) {
			addCriterion("codUrgencia >=", value, "codurgencia");
			return (Criteria) this;
		}

		public Criteria andCodurgenciaLessThan(Integer value) {
			addCriterion("codUrgencia <", value, "codurgencia");
			return (Criteria) this;
		}

		public Criteria andCodurgenciaLessThanOrEqualTo(Integer value) {
			addCriterion("codUrgencia <=", value, "codurgencia");
			return (Criteria) this;
		}

		public Criteria andCodurgenciaIn(List<Integer> values) {
			addCriterion("codUrgencia in", values, "codurgencia");
			return (Criteria) this;
		}

		public Criteria andCodurgenciaNotIn(List<Integer> values) {
			addCriterion("codUrgencia not in", values, "codurgencia");
			return (Criteria) this;
		}

		public Criteria andCodurgenciaBetween(Integer value1, Integer value2) {
			addCriterion("codUrgencia between", value1, value2, "codurgencia");
			return (Criteria) this;
		}

		public Criteria andCodurgenciaNotBetween(Integer value1, Integer value2) {
			addCriterion("codUrgencia not between", value1, value2,
					"codurgencia");
			return (Criteria) this;
		}

		public Criteria andAtendidoIsNull() {
			addCriterion("atendido is null");
			return (Criteria) this;
		}

		public Criteria andAtendidoIsNotNull() {
			addCriterion("atendido is not null");
			return (Criteria) this;
		}

		public Criteria andAtendidoEqualTo(Boolean value) {
			addCriterion("atendido =", value, "atendido");
			return (Criteria) this;
		}

		public Criteria andAtendidoNotEqualTo(Boolean value) {
			addCriterion("atendido <>", value, "atendido");
			return (Criteria) this;
		}

		public Criteria andAtendidoGreaterThan(Boolean value) {
			addCriterion("atendido >", value, "atendido");
			return (Criteria) this;
		}

		public Criteria andAtendidoGreaterThanOrEqualTo(Boolean value) {
			addCriterion("atendido >=", value, "atendido");
			return (Criteria) this;
		}

		public Criteria andAtendidoLessThan(Boolean value) {
			addCriterion("atendido <", value, "atendido");
			return (Criteria) this;
		}

		public Criteria andAtendidoLessThanOrEqualTo(Boolean value) {
			addCriterion("atendido <=", value, "atendido");
			return (Criteria) this;
		}

		public Criteria andAtendidoIn(List<Boolean> values) {
			addCriterion("atendido in", values, "atendido");
			return (Criteria) this;
		}

		public Criteria andAtendidoNotIn(List<Boolean> values) {
			addCriterion("atendido not in", values, "atendido");
			return (Criteria) this;
		}

		public Criteria andAtendidoBetween(Boolean value1, Boolean value2) {
			addCriterion("atendido between", value1, value2, "atendido");
			return (Criteria) this;
		}

		public Criteria andAtendidoNotBetween(Boolean value1, Boolean value2) {
			addCriterion("atendido not between", value1, value2, "atendido");
			return (Criteria) this;
		}

		public Criteria andCodfaseIsNull() {
			addCriterion("codFase is null");
			return (Criteria) this;
		}

		public Criteria andCodfaseIsNotNull() {
			addCriterion("codFase is not null");
			return (Criteria) this;
		}

		public Criteria andCodfaseEqualTo(Integer value) {
			addCriterion("codFase =", value, "codfase");
			return (Criteria) this;
		}

		public Criteria andCodfaseNotEqualTo(Integer value) {
			addCriterion("codFase <>", value, "codfase");
			return (Criteria) this;
		}

		public Criteria andCodfaseGreaterThan(Integer value) {
			addCriterion("codFase >", value, "codfase");
			return (Criteria) this;
		}

		public Criteria andCodfaseGreaterThanOrEqualTo(Integer value) {
			addCriterion("codFase >=", value, "codfase");
			return (Criteria) this;
		}

		public Criteria andCodfaseLessThan(Integer value) {
			addCriterion("codFase <", value, "codfase");
			return (Criteria) this;
		}

		public Criteria andCodfaseLessThanOrEqualTo(Integer value) {
			addCriterion("codFase <=", value, "codfase");
			return (Criteria) this;
		}

		public Criteria andCodfaseIn(List<Integer> values) {
			addCriterion("codFase in", values, "codfase");
			return (Criteria) this;
		}

		public Criteria andCodfaseNotIn(List<Integer> values) {
			addCriterion("codFase not in", values, "codfase");
			return (Criteria) this;
		}

		public Criteria andCodfaseBetween(Integer value1, Integer value2) {
			addCriterion("codFase between", value1, value2, "codfase");
			return (Criteria) this;
		}

		public Criteria andCodfaseNotBetween(Integer value1, Integer value2) {
			addCriterion("codFase not between", value1, value2, "codfase");
			return (Criteria) this;
		}

		public Criteria andCodptareaIsNull() {
			addCriterion("codPTarea is null");
			return (Criteria) this;
		}

		public Criteria andCodptareaIsNotNull() {
			addCriterion("codPTarea is not null");
			return (Criteria) this;
		}

		public Criteria andCodptareaEqualTo(Integer value) {
			addCriterion("codPTarea =", value, "codptarea");
			return (Criteria) this;
		}

		public Criteria andCodptareaNotEqualTo(Integer value) {
			addCriterion("codPTarea <>", value, "codptarea");
			return (Criteria) this;
		}

		public Criteria andCodptareaGreaterThan(Integer value) {
			addCriterion("codPTarea >", value, "codptarea");
			return (Criteria) this;
		}

		public Criteria andCodptareaGreaterThanOrEqualTo(Integer value) {
			addCriterion("codPTarea >=", value, "codptarea");
			return (Criteria) this;
		}

		public Criteria andCodptareaLessThan(Integer value) {
			addCriterion("codPTarea <", value, "codptarea");
			return (Criteria) this;
		}

		public Criteria andCodptareaLessThanOrEqualTo(Integer value) {
			addCriterion("codPTarea <=", value, "codptarea");
			return (Criteria) this;
		}

		public Criteria andCodptareaIn(List<Integer> values) {
			addCriterion("codPTarea in", values, "codptarea");
			return (Criteria) this;
		}

		public Criteria andCodptareaNotIn(List<Integer> values) {
			addCriterion("codPTarea not in", values, "codptarea");
			return (Criteria) this;
		}

		public Criteria andCodptareaBetween(Integer value1, Integer value2) {
			addCriterion("codPTarea between", value1, value2, "codptarea");
			return (Criteria) this;
		}

		public Criteria andCodptareaNotBetween(Integer value1, Integer value2) {
			addCriterion("codPTarea not between", value1, value2, "codptarea");
			return (Criteria) this;
		}

		public Criteria andProymanagerIsNull() {
			addCriterion("proyManager is null");
			return (Criteria) this;
		}

		public Criteria andProymanagerIsNotNull() {
			addCriterion("proyManager is not null");
			return (Criteria) this;
		}

		public Criteria andProymanagerEqualTo(Boolean value) {
			addCriterion("proyManager =", value, "proymanager");
			return (Criteria) this;
		}

		public Criteria andProymanagerNotEqualTo(Boolean value) {
			addCriterion("proyManager <>", value, "proymanager");
			return (Criteria) this;
		}

		public Criteria andProymanagerGreaterThan(Boolean value) {
			addCriterion("proyManager >", value, "proymanager");
			return (Criteria) this;
		}

		public Criteria andProymanagerGreaterThanOrEqualTo(Boolean value) {
			addCriterion("proyManager >=", value, "proymanager");
			return (Criteria) this;
		}

		public Criteria andProymanagerLessThan(Boolean value) {
			addCriterion("proyManager <", value, "proymanager");
			return (Criteria) this;
		}

		public Criteria andProymanagerLessThanOrEqualTo(Boolean value) {
			addCriterion("proyManager <=", value, "proymanager");
			return (Criteria) this;
		}

		public Criteria andProymanagerIn(List<Boolean> values) {
			addCriterion("proyManager in", values, "proymanager");
			return (Criteria) this;
		}

		public Criteria andProymanagerNotIn(List<Boolean> values) {
			addCriterion("proyManager not in", values, "proymanager");
			return (Criteria) this;
		}

		public Criteria andProymanagerBetween(Boolean value1, Boolean value2) {
			addCriterion("proyManager between", value1, value2, "proymanager");
			return (Criteria) this;
		}

		public Criteria andProymanagerNotBetween(Boolean value1, Boolean value2) {
			addCriterion("proyManager not between", value1, value2,
					"proymanager");
			return (Criteria) this;
		}

		public Criteria andFechacreacionIsNull() {
			addCriterion("fechaCreacion is null");
			return (Criteria) this;
		}

		public Criteria andFechacreacionIsNotNull() {
			addCriterion("fechaCreacion is not null");
			return (Criteria) this;
		}

		public Criteria andFechacreacionEqualTo(String value) {
			addCriterion("fechaCreacion =", value, "fechacreacion");
			return (Criteria) this;
		}

		public Criteria andFechacreacionNotEqualTo(String value) {
			addCriterion("fechaCreacion <>", value, "fechacreacion");
			return (Criteria) this;
		}

		public Criteria andFechacreacionGreaterThan(String value) {
			addCriterion("fechaCreacion >", value, "fechacreacion");
			return (Criteria) this;
		}

		public Criteria andFechacreacionGreaterThanOrEqualTo(String value) {
			addCriterion("fechaCreacion >=", value, "fechacreacion");
			return (Criteria) this;
		}

		public Criteria andFechacreacionLessThan(String value) {
			addCriterion("fechaCreacion <", value, "fechacreacion");
			return (Criteria) this;
		}

		public Criteria andFechacreacionLessThanOrEqualTo(String value) {
			addCriterion("fechaCreacion <=", value, "fechacreacion");
			return (Criteria) this;
		}

		public Criteria andFechacreacionIn(List<String> values) {
			addCriterion("fechaCreacion in", values, "fechacreacion");
			return (Criteria) this;
		}

		public Criteria andFechacreacionNotIn(List<String> values) {
			addCriterion("fechaCreacion not in", values, "fechacreacion");
			return (Criteria) this;
		}

		public Criteria andFechacreacionBetween(String value1, String value2) {
			addCriterion("fechaCreacion between", value1, value2,
					"fechacreacion");
			return (Criteria) this;
		}

		public Criteria andFechacreacionNotBetween(String value1, String value2) {
			addCriterion("fechaCreacion not between", value1, value2,
					"fechacreacion");
			return (Criteria) this;
		}

		public Criteria andFechaatencionIsNull() {
			addCriterion("fechaAtencion is null");
			return (Criteria) this;
		}

		public Criteria andFechaatencionIsNotNull() {
			addCriterion("fechaAtencion is not null");
			return (Criteria) this;
		}

		public Criteria andFechaatencionEqualTo(String value) {
			addCriterion("fechaAtencion =", value, "fechaatencion");
			return (Criteria) this;
		}

		public Criteria andFechaatencionNotEqualTo(String value) {
			addCriterion("fechaAtencion <>", value, "fechaatencion");
			return (Criteria) this;
		}

		public Criteria andFechaatencionGreaterThan(String value) {
			addCriterion("fechaAtencion >", value, "fechaatencion");
			return (Criteria) this;
		}

		public Criteria andFechaatencionGreaterThanOrEqualTo(String value) {
			addCriterion("fechaAtencion >=", value, "fechaatencion");
			return (Criteria) this;
		}

		public Criteria andFechaatencionLessThan(String value) {
			addCriterion("fechaAtencion <", value, "fechaatencion");
			return (Criteria) this;
		}

		public Criteria andFechaatencionLessThanOrEqualTo(String value) {
			addCriterion("fechaAtencion <=", value, "fechaatencion");
			return (Criteria) this;
		}

		public Criteria andFechaatencionIn(List<String> values) {
			addCriterion("fechaAtencion in", values, "fechaatencion");
			return (Criteria) this;
		}

		public Criteria andFechaatencionNotIn(List<String> values) {
			addCriterion("fechaAtencion not in", values, "fechaatencion");
			return (Criteria) this;
		}

		public Criteria andFechaatencionBetween(String value1, String value2) {
			addCriterion("fechaAtencion between", value1, value2,
					"fechaatencion");
			return (Criteria) this;
		}

		public Criteria andFechaatencionNotBetween(String value1, String value2) {
			addCriterion("fechaAtencion not between", value1, value2,
					"fechaatencion");
			return (Criteria) this;
		}

		public Criteria andActivoIsNull() {
			addCriterion("activo is null");
			return (Criteria) this;
		}

		public Criteria andActivoIsNotNull() {
			addCriterion("activo is not null");
			return (Criteria) this;
		}

		public Criteria andActivoEqualTo(Boolean value) {
			addCriterion("activo =", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoNotEqualTo(Boolean value) {
			addCriterion("activo <>", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoGreaterThan(Boolean value) {
			addCriterion("activo >", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoGreaterThanOrEqualTo(Boolean value) {
			addCriterion("activo >=", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoLessThan(Boolean value) {
			addCriterion("activo <", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoLessThanOrEqualTo(Boolean value) {
			addCriterion("activo <=", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoIn(List<Boolean> values) {
			addCriterion("activo in", values, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoNotIn(List<Boolean> values) {
			addCriterion("activo not in", values, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoBetween(Boolean value1, Boolean value2) {
			addCriterion("activo between", value1, value2, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoNotBetween(Boolean value1, Boolean value2) {
			addCriterion("activo not between", value1, value2, "activo");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table pincidencia
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pincidencia
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}