package com.pro.proyectospro.configuracion.domain;

public class Pincidencia {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pincidencia.codigo
	 * @mbggenerated
	 */
	private Integer codigo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pincidencia.des
	 * @mbggenerated
	 */
	private String des;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pincidencia.codUrgencia
	 * @mbggenerated
	 */
	private Integer codurgencia;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pincidencia.atendido
	 * @mbggenerated
	 */
	private Boolean atendido;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pincidencia.codFase
	 * @mbggenerated
	 */
	private Integer codfase;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pincidencia.codPTarea
	 * @mbggenerated
	 */
	private Integer codptarea;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pincidencia.proyManager
	 * @mbggenerated
	 */
	private Boolean proymanager;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pincidencia.fechaCreacion
	 * @mbggenerated
	 */
	private String fechacreacion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pincidencia.fechaAtencion
	 * @mbggenerated
	 */
	private String fechaatencion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pincidencia.activo
	 * @mbggenerated
	 */
	private Boolean activo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pincidencia.codigo
	 * @return  the value of pincidencia.codigo
	 * @mbggenerated
	 */
	public Integer getCodigo() {
		return codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pincidencia.codigo
	 * @param codigo  the value for pincidencia.codigo
	 * @mbggenerated
	 */
	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pincidencia.des
	 * @return  the value of pincidencia.des
	 * @mbggenerated
	 */
	public String getDes() {
		return des;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pincidencia.des
	 * @param des  the value for pincidencia.des
	 * @mbggenerated
	 */
	public void setDes(String des) {
		this.des = des;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pincidencia.codUrgencia
	 * @return  the value of pincidencia.codUrgencia
	 * @mbggenerated
	 */
	public Integer getCodurgencia() {
		return codurgencia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pincidencia.codUrgencia
	 * @param codurgencia  the value for pincidencia.codUrgencia
	 * @mbggenerated
	 */
	public void setCodurgencia(Integer codurgencia) {
		this.codurgencia = codurgencia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pincidencia.atendido
	 * @return  the value of pincidencia.atendido
	 * @mbggenerated
	 */
	public Boolean getAtendido() {
		return atendido;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pincidencia.atendido
	 * @param atendido  the value for pincidencia.atendido
	 * @mbggenerated
	 */
	public void setAtendido(Boolean atendido) {
		this.atendido = atendido;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pincidencia.codFase
	 * @return  the value of pincidencia.codFase
	 * @mbggenerated
	 */
	public Integer getCodfase() {
		return codfase;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pincidencia.codFase
	 * @param codfase  the value for pincidencia.codFase
	 * @mbggenerated
	 */
	public void setCodfase(Integer codfase) {
		this.codfase = codfase;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pincidencia.codPTarea
	 * @return  the value of pincidencia.codPTarea
	 * @mbggenerated
	 */
	public Integer getCodptarea() {
		return codptarea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pincidencia.codPTarea
	 * @param codptarea  the value for pincidencia.codPTarea
	 * @mbggenerated
	 */
	public void setCodptarea(Integer codptarea) {
		this.codptarea = codptarea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pincidencia.proyManager
	 * @return  the value of pincidencia.proyManager
	 * @mbggenerated
	 */
	public Boolean getProymanager() {
		return proymanager;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pincidencia.proyManager
	 * @param proymanager  the value for pincidencia.proyManager
	 * @mbggenerated
	 */
	public void setProymanager(Boolean proymanager) {
		this.proymanager = proymanager;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pincidencia.fechaCreacion
	 * @return  the value of pincidencia.fechaCreacion
	 * @mbggenerated
	 */
	public String getFechacreacion() {
		return fechacreacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pincidencia.fechaCreacion
	 * @param fechacreacion  the value for pincidencia.fechaCreacion
	 * @mbggenerated
	 */
	public void setFechacreacion(String fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pincidencia.fechaAtencion
	 * @return  the value of pincidencia.fechaAtencion
	 * @mbggenerated
	 */
	public String getFechaatencion() {
		return fechaatencion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pincidencia.fechaAtencion
	 * @param fechaatencion  the value for pincidencia.fechaAtencion
	 * @mbggenerated
	 */
	public void setFechaatencion(String fechaatencion) {
		this.fechaatencion = fechaatencion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pincidencia.activo
	 * @return  the value of pincidencia.activo
	 * @mbggenerated
	 */
	public Boolean getActivo() {
		return activo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pincidencia.activo
	 * @param activo  the value for pincidencia.activo
	 * @mbggenerated
	 */
	public void setActivo(Boolean activo) {
		this.activo = activo;
	}
}