package com.pro.proyectospro.configuracion.domain;

import java.util.ArrayList;
import java.util.List;

public class PmanagerproyectoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pmanagerproyecto
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pmanagerproyecto
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pmanagerproyecto
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pmanagerproyecto
	 * @mbggenerated
	 */
	public PmanagerproyectoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pmanagerproyecto
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pmanagerproyecto
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pmanagerproyecto
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pmanagerproyecto
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pmanagerproyecto
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pmanagerproyecto
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pmanagerproyecto
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pmanagerproyecto
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pmanagerproyecto
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pmanagerproyecto
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table pmanagerproyecto
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCodigoIsNull() {
			addCriterion("codigo is null");
			return (Criteria) this;
		}

		public Criteria andCodigoIsNotNull() {
			addCriterion("codigo is not null");
			return (Criteria) this;
		}

		public Criteria andCodigoEqualTo(Integer value) {
			addCriterion("codigo =", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoNotEqualTo(Integer value) {
			addCriterion("codigo <>", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoGreaterThan(Integer value) {
			addCriterion("codigo >", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoGreaterThanOrEqualTo(Integer value) {
			addCriterion("codigo >=", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoLessThan(Integer value) {
			addCriterion("codigo <", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoLessThanOrEqualTo(Integer value) {
			addCriterion("codigo <=", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoIn(List<Integer> values) {
			addCriterion("codigo in", values, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoNotIn(List<Integer> values) {
			addCriterion("codigo not in", values, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoBetween(Integer value1, Integer value2) {
			addCriterion("codigo between", value1, value2, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoNotBetween(Integer value1, Integer value2) {
			addCriterion("codigo not between", value1, value2, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodpmanagerIsNull() {
			addCriterion("codPManager is null");
			return (Criteria) this;
		}

		public Criteria andCodpmanagerIsNotNull() {
			addCriterion("codPManager is not null");
			return (Criteria) this;
		}

		public Criteria andCodpmanagerEqualTo(Integer value) {
			addCriterion("codPManager =", value, "codpmanager");
			return (Criteria) this;
		}

		public Criteria andCodpmanagerNotEqualTo(Integer value) {
			addCriterion("codPManager <>", value, "codpmanager");
			return (Criteria) this;
		}

		public Criteria andCodpmanagerGreaterThan(Integer value) {
			addCriterion("codPManager >", value, "codpmanager");
			return (Criteria) this;
		}

		public Criteria andCodpmanagerGreaterThanOrEqualTo(Integer value) {
			addCriterion("codPManager >=", value, "codpmanager");
			return (Criteria) this;
		}

		public Criteria andCodpmanagerLessThan(Integer value) {
			addCriterion("codPManager <", value, "codpmanager");
			return (Criteria) this;
		}

		public Criteria andCodpmanagerLessThanOrEqualTo(Integer value) {
			addCriterion("codPManager <=", value, "codpmanager");
			return (Criteria) this;
		}

		public Criteria andCodpmanagerIn(List<Integer> values) {
			addCriterion("codPManager in", values, "codpmanager");
			return (Criteria) this;
		}

		public Criteria andCodpmanagerNotIn(List<Integer> values) {
			addCriterion("codPManager not in", values, "codpmanager");
			return (Criteria) this;
		}

		public Criteria andCodpmanagerBetween(Integer value1, Integer value2) {
			addCriterion("codPManager between", value1, value2, "codpmanager");
			return (Criteria) this;
		}

		public Criteria andCodpmanagerNotBetween(Integer value1, Integer value2) {
			addCriterion("codPManager not between", value1, value2,
					"codpmanager");
			return (Criteria) this;
		}

		public Criteria andCodproyectoIsNull() {
			addCriterion("codProyecto is null");
			return (Criteria) this;
		}

		public Criteria andCodproyectoIsNotNull() {
			addCriterion("codProyecto is not null");
			return (Criteria) this;
		}

		public Criteria andCodproyectoEqualTo(Integer value) {
			addCriterion("codProyecto =", value, "codproyecto");
			return (Criteria) this;
		}

		public Criteria andCodproyectoNotEqualTo(Integer value) {
			addCriterion("codProyecto <>", value, "codproyecto");
			return (Criteria) this;
		}

		public Criteria andCodproyectoGreaterThan(Integer value) {
			addCriterion("codProyecto >", value, "codproyecto");
			return (Criteria) this;
		}

		public Criteria andCodproyectoGreaterThanOrEqualTo(Integer value) {
			addCriterion("codProyecto >=", value, "codproyecto");
			return (Criteria) this;
		}

		public Criteria andCodproyectoLessThan(Integer value) {
			addCriterion("codProyecto <", value, "codproyecto");
			return (Criteria) this;
		}

		public Criteria andCodproyectoLessThanOrEqualTo(Integer value) {
			addCriterion("codProyecto <=", value, "codproyecto");
			return (Criteria) this;
		}

		public Criteria andCodproyectoIn(List<Integer> values) {
			addCriterion("codProyecto in", values, "codproyecto");
			return (Criteria) this;
		}

		public Criteria andCodproyectoNotIn(List<Integer> values) {
			addCriterion("codProyecto not in", values, "codproyecto");
			return (Criteria) this;
		}

		public Criteria andCodproyectoBetween(Integer value1, Integer value2) {
			addCriterion("codProyecto between", value1, value2, "codproyecto");
			return (Criteria) this;
		}

		public Criteria andCodproyectoNotBetween(Integer value1, Integer value2) {
			addCriterion("codProyecto not between", value1, value2,
					"codproyecto");
			return (Criteria) this;
		}

		public Criteria andActivoIsNull() {
			addCriterion("activo is null");
			return (Criteria) this;
		}

		public Criteria andActivoIsNotNull() {
			addCriterion("activo is not null");
			return (Criteria) this;
		}

		public Criteria andActivoEqualTo(Boolean value) {
			addCriterion("activo =", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoNotEqualTo(Boolean value) {
			addCriterion("activo <>", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoGreaterThan(Boolean value) {
			addCriterion("activo >", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoGreaterThanOrEqualTo(Boolean value) {
			addCriterion("activo >=", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoLessThan(Boolean value) {
			addCriterion("activo <", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoLessThanOrEqualTo(Boolean value) {
			addCriterion("activo <=", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoIn(List<Boolean> values) {
			addCriterion("activo in", values, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoNotIn(List<Boolean> values) {
			addCriterion("activo not in", values, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoBetween(Boolean value1, Boolean value2) {
			addCriterion("activo between", value1, value2, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoNotBetween(Boolean value1, Boolean value2) {
			addCriterion("activo not between", value1, value2, "activo");
			return (Criteria) this;
		}

		public Criteria andFechaingresoIsNull() {
			addCriterion("fechaIngreso is null");
			return (Criteria) this;
		}

		public Criteria andFechaingresoIsNotNull() {
			addCriterion("fechaIngreso is not null");
			return (Criteria) this;
		}

		public Criteria andFechaingresoEqualTo(String value) {
			addCriterion("fechaIngreso =", value, "fechaingreso");
			return (Criteria) this;
		}

		public Criteria andFechaingresoNotEqualTo(String value) {
			addCriterion("fechaIngreso <>", value, "fechaingreso");
			return (Criteria) this;
		}

		public Criteria andFechaingresoGreaterThan(String value) {
			addCriterion("fechaIngreso >", value, "fechaingreso");
			return (Criteria) this;
		}

		public Criteria andFechaingresoGreaterThanOrEqualTo(String value) {
			addCriterion("fechaIngreso >=", value, "fechaingreso");
			return (Criteria) this;
		}

		public Criteria andFechaingresoLessThan(String value) {
			addCriterion("fechaIngreso <", value, "fechaingreso");
			return (Criteria) this;
		}

		public Criteria andFechaingresoLessThanOrEqualTo(String value) {
			addCriterion("fechaIngreso <=", value, "fechaingreso");
			return (Criteria) this;
		}

		public Criteria andFechaingresoIn(List<String> values) {
			addCriterion("fechaIngreso in", values, "fechaingreso");
			return (Criteria) this;
		}

		public Criteria andFechaingresoNotIn(List<String> values) {
			addCriterion("fechaIngreso not in", values, "fechaingreso");
			return (Criteria) this;
		}

		public Criteria andFechaingresoBetween(String value1, String value2) {
			addCriterion("fechaIngreso between", value1, value2, "fechaingreso");
			return (Criteria) this;
		}

		public Criteria andFechaingresoNotBetween(String value1, String value2) {
			addCriterion("fechaIngreso not between", value1, value2,
					"fechaingreso");
			return (Criteria) this;
		}

		public Criteria andFechadesactivacionIsNull() {
			addCriterion("fechaDesactivacion is null");
			return (Criteria) this;
		}

		public Criteria andFechadesactivacionIsNotNull() {
			addCriterion("fechaDesactivacion is not null");
			return (Criteria) this;
		}

		public Criteria andFechadesactivacionEqualTo(String value) {
			addCriterion("fechaDesactivacion =", value, "fechadesactivacion");
			return (Criteria) this;
		}

		public Criteria andFechadesactivacionNotEqualTo(String value) {
			addCriterion("fechaDesactivacion <>", value, "fechadesactivacion");
			return (Criteria) this;
		}

		public Criteria andFechadesactivacionGreaterThan(String value) {
			addCriterion("fechaDesactivacion >", value, "fechadesactivacion");
			return (Criteria) this;
		}

		public Criteria andFechadesactivacionGreaterThanOrEqualTo(String value) {
			addCriterion("fechaDesactivacion >=", value, "fechadesactivacion");
			return (Criteria) this;
		}

		public Criteria andFechadesactivacionLessThan(String value) {
			addCriterion("fechaDesactivacion <", value, "fechadesactivacion");
			return (Criteria) this;
		}

		public Criteria andFechadesactivacionLessThanOrEqualTo(String value) {
			addCriterion("fechaDesactivacion <=", value, "fechadesactivacion");
			return (Criteria) this;
		}

		public Criteria andFechadesactivacionIn(List<String> values) {
			addCriterion("fechaDesactivacion in", values, "fechadesactivacion");
			return (Criteria) this;
		}

		public Criteria andFechadesactivacionNotIn(List<String> values) {
			addCriterion("fechaDesactivacion not in", values,
					"fechadesactivacion");
			return (Criteria) this;
		}

		public Criteria andFechadesactivacionBetween(String value1,
				String value2) {
			addCriterion("fechaDesactivacion between", value1, value2,
					"fechadesactivacion");
			return (Criteria) this;
		}

		public Criteria andFechadesactivacionNotBetween(String value1,
				String value2) {
			addCriterion("fechaDesactivacion not between", value1, value2,
					"fechadesactivacion");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table pmanagerproyecto
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pmanagerproyecto
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}