package com.pro.proyectospro.configuracion.domain;

public class Pmanagerproyecto {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pmanagerproyecto.codigo
	 * @mbggenerated
	 */
	private Integer codigo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pmanagerproyecto.codPManager
	 * @mbggenerated
	 */
	private Integer codpmanager;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pmanagerproyecto.codProyecto
	 * @mbggenerated
	 */
	private Integer codproyecto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pmanagerproyecto.activo
	 * @mbggenerated
	 */
	private Boolean activo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pmanagerproyecto.fechaIngreso
	 * @mbggenerated
	 */
	private String fechaingreso;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pmanagerproyecto.fechaDesactivacion
	 * @mbggenerated
	 */
	private String fechadesactivacion;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pmanagerproyecto.codigo
	 * @return  the value of pmanagerproyecto.codigo
	 * @mbggenerated
	 */
	public Integer getCodigo() {
		return codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pmanagerproyecto.codigo
	 * @param codigo  the value for pmanagerproyecto.codigo
	 * @mbggenerated
	 */
	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pmanagerproyecto.codPManager
	 * @return  the value of pmanagerproyecto.codPManager
	 * @mbggenerated
	 */
	public Integer getCodpmanager() {
		return codpmanager;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pmanagerproyecto.codPManager
	 * @param codpmanager  the value for pmanagerproyecto.codPManager
	 * @mbggenerated
	 */
	public void setCodpmanager(Integer codpmanager) {
		this.codpmanager = codpmanager;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pmanagerproyecto.codProyecto
	 * @return  the value of pmanagerproyecto.codProyecto
	 * @mbggenerated
	 */
	public Integer getCodproyecto() {
		return codproyecto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pmanagerproyecto.codProyecto
	 * @param codproyecto  the value for pmanagerproyecto.codProyecto
	 * @mbggenerated
	 */
	public void setCodproyecto(Integer codproyecto) {
		this.codproyecto = codproyecto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pmanagerproyecto.activo
	 * @return  the value of pmanagerproyecto.activo
	 * @mbggenerated
	 */
	public Boolean getActivo() {
		return activo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pmanagerproyecto.activo
	 * @param activo  the value for pmanagerproyecto.activo
	 * @mbggenerated
	 */
	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pmanagerproyecto.fechaIngreso
	 * @return  the value of pmanagerproyecto.fechaIngreso
	 * @mbggenerated
	 */
	public String getFechaingreso() {
		return fechaingreso;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pmanagerproyecto.fechaIngreso
	 * @param fechaingreso  the value for pmanagerproyecto.fechaIngreso
	 * @mbggenerated
	 */
	public void setFechaingreso(String fechaingreso) {
		this.fechaingreso = fechaingreso;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pmanagerproyecto.fechaDesactivacion
	 * @return  the value of pmanagerproyecto.fechaDesactivacion
	 * @mbggenerated
	 */
	public String getFechadesactivacion() {
		return fechadesactivacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pmanagerproyecto.fechaDesactivacion
	 * @param fechadesactivacion  the value for pmanagerproyecto.fechaDesactivacion
	 * @mbggenerated
	 */
	public void setFechadesactivacion(String fechadesactivacion) {
		this.fechadesactivacion = fechadesactivacion;
	}
}