package com.pro.proyectospro.configuracion.domain;

public class Pmanager {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pmanager.codigo
	 * @mbggenerated
	 */
	private Integer codigo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pmanager.codUsuario
	 * @mbggenerated
	 */
	private Integer codusuario;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pmanager.codDatosPersona
	 * @mbggenerated
	 */
	private Integer coddatospersona;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pmanager.activo
	 * @mbggenerated
	 */
	private Boolean activo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pmanager.codigo
	 * @return  the value of pmanager.codigo
	 * @mbggenerated
	 */
	public Integer getCodigo() {
		return codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pmanager.codigo
	 * @param codigo  the value for pmanager.codigo
	 * @mbggenerated
	 */
	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pmanager.codUsuario
	 * @return  the value of pmanager.codUsuario
	 * @mbggenerated
	 */
	public Integer getCodusuario() {
		return codusuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pmanager.codUsuario
	 * @param codusuario  the value for pmanager.codUsuario
	 * @mbggenerated
	 */
	public void setCodusuario(Integer codusuario) {
		this.codusuario = codusuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pmanager.codDatosPersona
	 * @return  the value of pmanager.codDatosPersona
	 * @mbggenerated
	 */
	public Integer getCoddatospersona() {
		return coddatospersona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pmanager.codDatosPersona
	 * @param coddatospersona  the value for pmanager.codDatosPersona
	 * @mbggenerated
	 */
	public void setCoddatospersona(Integer coddatospersona) {
		this.coddatospersona = coddatospersona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pmanager.activo
	 * @return  the value of pmanager.activo
	 * @mbggenerated
	 */
	public Boolean getActivo() {
		return activo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pmanager.activo
	 * @param activo  the value for pmanager.activo
	 * @mbggenerated
	 */
	public void setActivo(Boolean activo) {
		this.activo = activo;
	}
}