package com.pro.proyectospro.configuracion.domain;

import java.util.ArrayList;
import java.util.List;

public class PortafolioExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table portafolio
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table portafolio
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table portafolio
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portafolio
	 * @mbggenerated
	 */
	public PortafolioExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portafolio
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portafolio
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portafolio
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portafolio
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portafolio
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portafolio
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portafolio
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portafolio
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portafolio
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portafolio
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table portafolio
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCodigoIsNull() {
			addCriterion("codigo is null");
			return (Criteria) this;
		}

		public Criteria andCodigoIsNotNull() {
			addCriterion("codigo is not null");
			return (Criteria) this;
		}

		public Criteria andCodigoEqualTo(Integer value) {
			addCriterion("codigo =", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoNotEqualTo(Integer value) {
			addCriterion("codigo <>", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoGreaterThan(Integer value) {
			addCriterion("codigo >", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoGreaterThanOrEqualTo(Integer value) {
			addCriterion("codigo >=", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoLessThan(Integer value) {
			addCriterion("codigo <", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoLessThanOrEqualTo(Integer value) {
			addCriterion("codigo <=", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoIn(List<Integer> values) {
			addCriterion("codigo in", values, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoNotIn(List<Integer> values) {
			addCriterion("codigo not in", values, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoBetween(Integer value1, Integer value2) {
			addCriterion("codigo between", value1, value2, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoNotBetween(Integer value1, Integer value2) {
			addCriterion("codigo not between", value1, value2, "codigo");
			return (Criteria) this;
		}

		public Criteria andNombreIsNull() {
			addCriterion("nombre is null");
			return (Criteria) this;
		}

		public Criteria andNombreIsNotNull() {
			addCriterion("nombre is not null");
			return (Criteria) this;
		}

		public Criteria andNombreEqualTo(String value) {
			addCriterion("nombre =", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotEqualTo(String value) {
			addCriterion("nombre <>", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreGreaterThan(String value) {
			addCriterion("nombre >", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreGreaterThanOrEqualTo(String value) {
			addCriterion("nombre >=", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreLessThan(String value) {
			addCriterion("nombre <", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreLessThanOrEqualTo(String value) {
			addCriterion("nombre <=", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreLike(String value) {
			addCriterion("nombre like", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotLike(String value) {
			addCriterion("nombre not like", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreIn(List<String> values) {
			addCriterion("nombre in", values, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotIn(List<String> values) {
			addCriterion("nombre not in", values, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreBetween(String value1, String value2) {
			addCriterion("nombre between", value1, value2, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotBetween(String value1, String value2) {
			addCriterion("nombre not between", value1, value2, "nombre");
			return (Criteria) this;
		}

		public Criteria andDesIsNull() {
			addCriterion("des is null");
			return (Criteria) this;
		}

		public Criteria andDesIsNotNull() {
			addCriterion("des is not null");
			return (Criteria) this;
		}

		public Criteria andDesEqualTo(String value) {
			addCriterion("des =", value, "des");
			return (Criteria) this;
		}

		public Criteria andDesNotEqualTo(String value) {
			addCriterion("des <>", value, "des");
			return (Criteria) this;
		}

		public Criteria andDesGreaterThan(String value) {
			addCriterion("des >", value, "des");
			return (Criteria) this;
		}

		public Criteria andDesGreaterThanOrEqualTo(String value) {
			addCriterion("des >=", value, "des");
			return (Criteria) this;
		}

		public Criteria andDesLessThan(String value) {
			addCriterion("des <", value, "des");
			return (Criteria) this;
		}

		public Criteria andDesLessThanOrEqualTo(String value) {
			addCriterion("des <=", value, "des");
			return (Criteria) this;
		}

		public Criteria andDesLike(String value) {
			addCriterion("des like", value, "des");
			return (Criteria) this;
		}

		public Criteria andDesNotLike(String value) {
			addCriterion("des not like", value, "des");
			return (Criteria) this;
		}

		public Criteria andDesIn(List<String> values) {
			addCriterion("des in", values, "des");
			return (Criteria) this;
		}

		public Criteria andDesNotIn(List<String> values) {
			addCriterion("des not in", values, "des");
			return (Criteria) this;
		}

		public Criteria andDesBetween(String value1, String value2) {
			addCriterion("des between", value1, value2, "des");
			return (Criteria) this;
		}

		public Criteria andDesNotBetween(String value1, String value2) {
			addCriterion("des not between", value1, value2, "des");
			return (Criteria) this;
		}

		public Criteria andCodpmanagerIsNull() {
			addCriterion("codPManager is null");
			return (Criteria) this;
		}

		public Criteria andCodpmanagerIsNotNull() {
			addCriterion("codPManager is not null");
			return (Criteria) this;
		}

		public Criteria andCodpmanagerEqualTo(Integer value) {
			addCriterion("codPManager =", value, "codpmanager");
			return (Criteria) this;
		}

		public Criteria andCodpmanagerNotEqualTo(Integer value) {
			addCriterion("codPManager <>", value, "codpmanager");
			return (Criteria) this;
		}

		public Criteria andCodpmanagerGreaterThan(Integer value) {
			addCriterion("codPManager >", value, "codpmanager");
			return (Criteria) this;
		}

		public Criteria andCodpmanagerGreaterThanOrEqualTo(Integer value) {
			addCriterion("codPManager >=", value, "codpmanager");
			return (Criteria) this;
		}

		public Criteria andCodpmanagerLessThan(Integer value) {
			addCriterion("codPManager <", value, "codpmanager");
			return (Criteria) this;
		}

		public Criteria andCodpmanagerLessThanOrEqualTo(Integer value) {
			addCriterion("codPManager <=", value, "codpmanager");
			return (Criteria) this;
		}

		public Criteria andCodpmanagerIn(List<Integer> values) {
			addCriterion("codPManager in", values, "codpmanager");
			return (Criteria) this;
		}

		public Criteria andCodpmanagerNotIn(List<Integer> values) {
			addCriterion("codPManager not in", values, "codpmanager");
			return (Criteria) this;
		}

		public Criteria andCodpmanagerBetween(Integer value1, Integer value2) {
			addCriterion("codPManager between", value1, value2, "codpmanager");
			return (Criteria) this;
		}

		public Criteria andCodpmanagerNotBetween(Integer value1, Integer value2) {
			addCriterion("codPManager not between", value1, value2,
					"codpmanager");
			return (Criteria) this;
		}

		public Criteria andCodgerenteIsNull() {
			addCriterion("codGerente is null");
			return (Criteria) this;
		}

		public Criteria andCodgerenteIsNotNull() {
			addCriterion("codGerente is not null");
			return (Criteria) this;
		}

		public Criteria andCodgerenteEqualTo(Integer value) {
			addCriterion("codGerente =", value, "codgerente");
			return (Criteria) this;
		}

		public Criteria andCodgerenteNotEqualTo(Integer value) {
			addCriterion("codGerente <>", value, "codgerente");
			return (Criteria) this;
		}

		public Criteria andCodgerenteGreaterThan(Integer value) {
			addCriterion("codGerente >", value, "codgerente");
			return (Criteria) this;
		}

		public Criteria andCodgerenteGreaterThanOrEqualTo(Integer value) {
			addCriterion("codGerente >=", value, "codgerente");
			return (Criteria) this;
		}

		public Criteria andCodgerenteLessThan(Integer value) {
			addCriterion("codGerente <", value, "codgerente");
			return (Criteria) this;
		}

		public Criteria andCodgerenteLessThanOrEqualTo(Integer value) {
			addCriterion("codGerente <=", value, "codgerente");
			return (Criteria) this;
		}

		public Criteria andCodgerenteIn(List<Integer> values) {
			addCriterion("codGerente in", values, "codgerente");
			return (Criteria) this;
		}

		public Criteria andCodgerenteNotIn(List<Integer> values) {
			addCriterion("codGerente not in", values, "codgerente");
			return (Criteria) this;
		}

		public Criteria andCodgerenteBetween(Integer value1, Integer value2) {
			addCriterion("codGerente between", value1, value2, "codgerente");
			return (Criteria) this;
		}

		public Criteria andCodgerenteNotBetween(Integer value1, Integer value2) {
			addCriterion("codGerente not between", value1, value2, "codgerente");
			return (Criteria) this;
		}

		public Criteria andFechacreadoIsNull() {
			addCriterion("fechaCreado is null");
			return (Criteria) this;
		}

		public Criteria andFechacreadoIsNotNull() {
			addCriterion("fechaCreado is not null");
			return (Criteria) this;
		}

		public Criteria andFechacreadoEqualTo(String value) {
			addCriterion("fechaCreado =", value, "fechacreado");
			return (Criteria) this;
		}

		public Criteria andFechacreadoNotEqualTo(String value) {
			addCriterion("fechaCreado <>", value, "fechacreado");
			return (Criteria) this;
		}

		public Criteria andFechacreadoGreaterThan(String value) {
			addCriterion("fechaCreado >", value, "fechacreado");
			return (Criteria) this;
		}

		public Criteria andFechacreadoGreaterThanOrEqualTo(String value) {
			addCriterion("fechaCreado >=", value, "fechacreado");
			return (Criteria) this;
		}

		public Criteria andFechacreadoLessThan(String value) {
			addCriterion("fechaCreado <", value, "fechacreado");
			return (Criteria) this;
		}

		public Criteria andFechacreadoLessThanOrEqualTo(String value) {
			addCriterion("fechaCreado <=", value, "fechacreado");
			return (Criteria) this;
		}

		public Criteria andFechacreadoIn(List<String> values) {
			addCriterion("fechaCreado in", values, "fechacreado");
			return (Criteria) this;
		}

		public Criteria andFechacreadoNotIn(List<String> values) {
			addCriterion("fechaCreado not in", values, "fechacreado");
			return (Criteria) this;
		}

		public Criteria andFechacreadoBetween(String value1, String value2) {
			addCriterion("fechaCreado between", value1, value2, "fechacreado");
			return (Criteria) this;
		}

		public Criteria andFechacreadoNotBetween(String value1, String value2) {
			addCriterion("fechaCreado not between", value1, value2,
					"fechacreado");
			return (Criteria) this;
		}

		public Criteria andActivoIsNull() {
			addCriterion("activo is null");
			return (Criteria) this;
		}

		public Criteria andActivoIsNotNull() {
			addCriterion("activo is not null");
			return (Criteria) this;
		}

		public Criteria andActivoEqualTo(Boolean value) {
			addCriterion("activo =", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoNotEqualTo(Boolean value) {
			addCriterion("activo <>", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoGreaterThan(Boolean value) {
			addCriterion("activo >", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoGreaterThanOrEqualTo(Boolean value) {
			addCriterion("activo >=", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoLessThan(Boolean value) {
			addCriterion("activo <", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoLessThanOrEqualTo(Boolean value) {
			addCriterion("activo <=", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoIn(List<Boolean> values) {
			addCriterion("activo in", values, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoNotIn(List<Boolean> values) {
			addCriterion("activo not in", values, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoBetween(Boolean value1, Boolean value2) {
			addCriterion("activo between", value1, value2, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoNotBetween(Boolean value1, Boolean value2) {
			addCriterion("activo not between", value1, value2, "activo");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table portafolio
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table portafolio
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}