package com.pro.proyectospro.configuracion.domain;

public class Portafolio {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portafolio.codigo
	 * @mbggenerated
	 */
	private Integer codigo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portafolio.nombre
	 * @mbggenerated
	 */
	private String nombre;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portafolio.des
	 * @mbggenerated
	 */
	private String des;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portafolio.codPManager
	 * @mbggenerated
	 */
	private Integer codpmanager;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portafolio.codGerente
	 * @mbggenerated
	 */
	private Integer codgerente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portafolio.fechaCreado
	 * @mbggenerated
	 */
	private String fechacreado;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column portafolio.activo
	 * @mbggenerated
	 */
	private Boolean activo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portafolio.codigo
	 * @return  the value of portafolio.codigo
	 * @mbggenerated
	 */
	public Integer getCodigo() {
		return codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portafolio.codigo
	 * @param codigo  the value for portafolio.codigo
	 * @mbggenerated
	 */
	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portafolio.nombre
	 * @return  the value of portafolio.nombre
	 * @mbggenerated
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portafolio.nombre
	 * @param nombre  the value for portafolio.nombre
	 * @mbggenerated
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portafolio.des
	 * @return  the value of portafolio.des
	 * @mbggenerated
	 */
	public String getDes() {
		return des;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portafolio.des
	 * @param des  the value for portafolio.des
	 * @mbggenerated
	 */
	public void setDes(String des) {
		this.des = des;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portafolio.codPManager
	 * @return  the value of portafolio.codPManager
	 * @mbggenerated
	 */
	public Integer getCodpmanager() {
		return codpmanager;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portafolio.codPManager
	 * @param codpmanager  the value for portafolio.codPManager
	 * @mbggenerated
	 */
	public void setCodpmanager(Integer codpmanager) {
		this.codpmanager = codpmanager;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portafolio.codGerente
	 * @return  the value of portafolio.codGerente
	 * @mbggenerated
	 */
	public Integer getCodgerente() {
		return codgerente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portafolio.codGerente
	 * @param codgerente  the value for portafolio.codGerente
	 * @mbggenerated
	 */
	public void setCodgerente(Integer codgerente) {
		this.codgerente = codgerente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portafolio.fechaCreado
	 * @return  the value of portafolio.fechaCreado
	 * @mbggenerated
	 */
	public String getFechacreado() {
		return fechacreado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portafolio.fechaCreado
	 * @param fechacreado  the value for portafolio.fechaCreado
	 * @mbggenerated
	 */
	public void setFechacreado(String fechacreado) {
		this.fechacreado = fechacreado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column portafolio.activo
	 * @return  the value of portafolio.activo
	 * @mbggenerated
	 */
	public Boolean getActivo() {
		return activo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column portafolio.activo
	 * @param activo  the value for portafolio.activo
	 * @mbggenerated
	 */
	public void setActivo(Boolean activo) {
		this.activo = activo;
	}
}