package com.pro.proyectospro.configuracion.domain;

public class Precursoxgrupot {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column precursoxgrupot.codigo
	 * @mbggenerated
	 */
	private Integer codigo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column precursoxgrupot.codRecurso
	 * @mbggenerated
	 */
	private Integer codrecurso;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column precursoxgrupot.codATarea
	 * @mbggenerated
	 */
	private Integer codatarea;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column precursoxgrupot.activo
	 * @mbggenerated
	 */
	private Boolean activo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column precursoxgrupot.codigo
	 * @return  the value of precursoxgrupot.codigo
	 * @mbggenerated
	 */
	public Integer getCodigo() {
		return codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column precursoxgrupot.codigo
	 * @param codigo  the value for precursoxgrupot.codigo
	 * @mbggenerated
	 */
	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column precursoxgrupot.codRecurso
	 * @return  the value of precursoxgrupot.codRecurso
	 * @mbggenerated
	 */
	public Integer getCodrecurso() {
		return codrecurso;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column precursoxgrupot.codRecurso
	 * @param codrecurso  the value for precursoxgrupot.codRecurso
	 * @mbggenerated
	 */
	public void setCodrecurso(Integer codrecurso) {
		this.codrecurso = codrecurso;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column precursoxgrupot.codATarea
	 * @return  the value of precursoxgrupot.codATarea
	 * @mbggenerated
	 */
	public Integer getCodatarea() {
		return codatarea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column precursoxgrupot.codATarea
	 * @param codatarea  the value for precursoxgrupot.codATarea
	 * @mbggenerated
	 */
	public void setCodatarea(Integer codatarea) {
		this.codatarea = codatarea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column precursoxgrupot.activo
	 * @return  the value of precursoxgrupot.activo
	 * @mbggenerated
	 */
	public Boolean getActivo() {
		return activo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column precursoxgrupot.activo
	 * @param activo  the value for precursoxgrupot.activo
	 * @mbggenerated
	 */
	public void setActivo(Boolean activo) {
		this.activo = activo;
	}
}