package com.pro.proyectospro.configuracion.domain;

import java.util.ArrayList;
import java.util.List;

public class ProyectoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table proyecto
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table proyecto
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table proyecto
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proyecto
	 * @mbggenerated
	 */
	public ProyectoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proyecto
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proyecto
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proyecto
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proyecto
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proyecto
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proyecto
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proyecto
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proyecto
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proyecto
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proyecto
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table proyecto
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCodigoIsNull() {
			addCriterion("codigo is null");
			return (Criteria) this;
		}

		public Criteria andCodigoIsNotNull() {
			addCriterion("codigo is not null");
			return (Criteria) this;
		}

		public Criteria andCodigoEqualTo(Integer value) {
			addCriterion("codigo =", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoNotEqualTo(Integer value) {
			addCriterion("codigo <>", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoGreaterThan(Integer value) {
			addCriterion("codigo >", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoGreaterThanOrEqualTo(Integer value) {
			addCriterion("codigo >=", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoLessThan(Integer value) {
			addCriterion("codigo <", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoLessThanOrEqualTo(Integer value) {
			addCriterion("codigo <=", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoIn(List<Integer> values) {
			addCriterion("codigo in", values, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoNotIn(List<Integer> values) {
			addCriterion("codigo not in", values, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoBetween(Integer value1, Integer value2) {
			addCriterion("codigo between", value1, value2, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoNotBetween(Integer value1, Integer value2) {
			addCriterion("codigo not between", value1, value2, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodpportafolioIsNull() {
			addCriterion("codPPortafolio is null");
			return (Criteria) this;
		}

		public Criteria andCodpportafolioIsNotNull() {
			addCriterion("codPPortafolio is not null");
			return (Criteria) this;
		}

		public Criteria andCodpportafolioEqualTo(Integer value) {
			addCriterion("codPPortafolio =", value, "codpportafolio");
			return (Criteria) this;
		}

		public Criteria andCodpportafolioNotEqualTo(Integer value) {
			addCriterion("codPPortafolio <>", value, "codpportafolio");
			return (Criteria) this;
		}

		public Criteria andCodpportafolioGreaterThan(Integer value) {
			addCriterion("codPPortafolio >", value, "codpportafolio");
			return (Criteria) this;
		}

		public Criteria andCodpportafolioGreaterThanOrEqualTo(Integer value) {
			addCriterion("codPPortafolio >=", value, "codpportafolio");
			return (Criteria) this;
		}

		public Criteria andCodpportafolioLessThan(Integer value) {
			addCriterion("codPPortafolio <", value, "codpportafolio");
			return (Criteria) this;
		}

		public Criteria andCodpportafolioLessThanOrEqualTo(Integer value) {
			addCriterion("codPPortafolio <=", value, "codpportafolio");
			return (Criteria) this;
		}

		public Criteria andCodpportafolioIn(List<Integer> values) {
			addCriterion("codPPortafolio in", values, "codpportafolio");
			return (Criteria) this;
		}

		public Criteria andCodpportafolioNotIn(List<Integer> values) {
			addCriterion("codPPortafolio not in", values, "codpportafolio");
			return (Criteria) this;
		}

		public Criteria andCodpportafolioBetween(Integer value1, Integer value2) {
			addCriterion("codPPortafolio between", value1, value2,
					"codpportafolio");
			return (Criteria) this;
		}

		public Criteria andCodpportafolioNotBetween(Integer value1,
				Integer value2) {
			addCriterion("codPPortafolio not between", value1, value2,
					"codpportafolio");
			return (Criteria) this;
		}

		public Criteria andNombreIsNull() {
			addCriterion("nombre is null");
			return (Criteria) this;
		}

		public Criteria andNombreIsNotNull() {
			addCriterion("nombre is not null");
			return (Criteria) this;
		}

		public Criteria andNombreEqualTo(String value) {
			addCriterion("nombre =", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotEqualTo(String value) {
			addCriterion("nombre <>", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreGreaterThan(String value) {
			addCriterion("nombre >", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreGreaterThanOrEqualTo(String value) {
			addCriterion("nombre >=", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreLessThan(String value) {
			addCriterion("nombre <", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreLessThanOrEqualTo(String value) {
			addCriterion("nombre <=", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreLike(String value) {
			addCriterion("nombre like", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotLike(String value) {
			addCriterion("nombre not like", value, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreIn(List<String> values) {
			addCriterion("nombre in", values, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotIn(List<String> values) {
			addCriterion("nombre not in", values, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreBetween(String value1, String value2) {
			addCriterion("nombre between", value1, value2, "nombre");
			return (Criteria) this;
		}

		public Criteria andNombreNotBetween(String value1, String value2) {
			addCriterion("nombre not between", value1, value2, "nombre");
			return (Criteria) this;
		}

		public Criteria andDesIsNull() {
			addCriterion("des is null");
			return (Criteria) this;
		}

		public Criteria andDesIsNotNull() {
			addCriterion("des is not null");
			return (Criteria) this;
		}

		public Criteria andDesEqualTo(String value) {
			addCriterion("des =", value, "des");
			return (Criteria) this;
		}

		public Criteria andDesNotEqualTo(String value) {
			addCriterion("des <>", value, "des");
			return (Criteria) this;
		}

		public Criteria andDesGreaterThan(String value) {
			addCriterion("des >", value, "des");
			return (Criteria) this;
		}

		public Criteria andDesGreaterThanOrEqualTo(String value) {
			addCriterion("des >=", value, "des");
			return (Criteria) this;
		}

		public Criteria andDesLessThan(String value) {
			addCriterion("des <", value, "des");
			return (Criteria) this;
		}

		public Criteria andDesLessThanOrEqualTo(String value) {
			addCriterion("des <=", value, "des");
			return (Criteria) this;
		}

		public Criteria andDesLike(String value) {
			addCriterion("des like", value, "des");
			return (Criteria) this;
		}

		public Criteria andDesNotLike(String value) {
			addCriterion("des not like", value, "des");
			return (Criteria) this;
		}

		public Criteria andDesIn(List<String> values) {
			addCriterion("des in", values, "des");
			return (Criteria) this;
		}

		public Criteria andDesNotIn(List<String> values) {
			addCriterion("des not in", values, "des");
			return (Criteria) this;
		}

		public Criteria andDesBetween(String value1, String value2) {
			addCriterion("des between", value1, value2, "des");
			return (Criteria) this;
		}

		public Criteria andDesNotBetween(String value1, String value2) {
			addCriterion("des not between", value1, value2, "des");
			return (Criteria) this;
		}

		public Criteria andDesdeceroIsNull() {
			addCriterion("desdeCero is null");
			return (Criteria) this;
		}

		public Criteria andDesdeceroIsNotNull() {
			addCriterion("desdeCero is not null");
			return (Criteria) this;
		}

		public Criteria andDesdeceroEqualTo(Boolean value) {
			addCriterion("desdeCero =", value, "desdecero");
			return (Criteria) this;
		}

		public Criteria andDesdeceroNotEqualTo(Boolean value) {
			addCriterion("desdeCero <>", value, "desdecero");
			return (Criteria) this;
		}

		public Criteria andDesdeceroGreaterThan(Boolean value) {
			addCriterion("desdeCero >", value, "desdecero");
			return (Criteria) this;
		}

		public Criteria andDesdeceroGreaterThanOrEqualTo(Boolean value) {
			addCriterion("desdeCero >=", value, "desdecero");
			return (Criteria) this;
		}

		public Criteria andDesdeceroLessThan(Boolean value) {
			addCriterion("desdeCero <", value, "desdecero");
			return (Criteria) this;
		}

		public Criteria andDesdeceroLessThanOrEqualTo(Boolean value) {
			addCriterion("desdeCero <=", value, "desdecero");
			return (Criteria) this;
		}

		public Criteria andDesdeceroIn(List<Boolean> values) {
			addCriterion("desdeCero in", values, "desdecero");
			return (Criteria) this;
		}

		public Criteria andDesdeceroNotIn(List<Boolean> values) {
			addCriterion("desdeCero not in", values, "desdecero");
			return (Criteria) this;
		}

		public Criteria andDesdeceroBetween(Boolean value1, Boolean value2) {
			addCriterion("desdeCero between", value1, value2, "desdecero");
			return (Criteria) this;
		}

		public Criteria andDesdeceroNotBetween(Boolean value1, Boolean value2) {
			addCriterion("desdeCero not between", value1, value2, "desdecero");
			return (Criteria) this;
		}

		public Criteria andCodestadoIsNull() {
			addCriterion("codEstado is null");
			return (Criteria) this;
		}

		public Criteria andCodestadoIsNotNull() {
			addCriterion("codEstado is not null");
			return (Criteria) this;
		}

		public Criteria andCodestadoEqualTo(Integer value) {
			addCriterion("codEstado =", value, "codestado");
			return (Criteria) this;
		}

		public Criteria andCodestadoNotEqualTo(Integer value) {
			addCriterion("codEstado <>", value, "codestado");
			return (Criteria) this;
		}

		public Criteria andCodestadoGreaterThan(Integer value) {
			addCriterion("codEstado >", value, "codestado");
			return (Criteria) this;
		}

		public Criteria andCodestadoGreaterThanOrEqualTo(Integer value) {
			addCriterion("codEstado >=", value, "codestado");
			return (Criteria) this;
		}

		public Criteria andCodestadoLessThan(Integer value) {
			addCriterion("codEstado <", value, "codestado");
			return (Criteria) this;
		}

		public Criteria andCodestadoLessThanOrEqualTo(Integer value) {
			addCriterion("codEstado <=", value, "codestado");
			return (Criteria) this;
		}

		public Criteria andCodestadoIn(List<Integer> values) {
			addCriterion("codEstado in", values, "codestado");
			return (Criteria) this;
		}

		public Criteria andCodestadoNotIn(List<Integer> values) {
			addCriterion("codEstado not in", values, "codestado");
			return (Criteria) this;
		}

		public Criteria andCodestadoBetween(Integer value1, Integer value2) {
			addCriterion("codEstado between", value1, value2, "codestado");
			return (Criteria) this;
		}

		public Criteria andCodestadoNotBetween(Integer value1, Integer value2) {
			addCriterion("codEstado not between", value1, value2, "codestado");
			return (Criteria) this;
		}

		public Criteria andFechacreadoIsNull() {
			addCriterion("fechaCreado is null");
			return (Criteria) this;
		}

		public Criteria andFechacreadoIsNotNull() {
			addCriterion("fechaCreado is not null");
			return (Criteria) this;
		}

		public Criteria andFechacreadoEqualTo(String value) {
			addCriterion("fechaCreado =", value, "fechacreado");
			return (Criteria) this;
		}

		public Criteria andFechacreadoNotEqualTo(String value) {
			addCriterion("fechaCreado <>", value, "fechacreado");
			return (Criteria) this;
		}

		public Criteria andFechacreadoGreaterThan(String value) {
			addCriterion("fechaCreado >", value, "fechacreado");
			return (Criteria) this;
		}

		public Criteria andFechacreadoGreaterThanOrEqualTo(String value) {
			addCriterion("fechaCreado >=", value, "fechacreado");
			return (Criteria) this;
		}

		public Criteria andFechacreadoLessThan(String value) {
			addCriterion("fechaCreado <", value, "fechacreado");
			return (Criteria) this;
		}

		public Criteria andFechacreadoLessThanOrEqualTo(String value) {
			addCriterion("fechaCreado <=", value, "fechacreado");
			return (Criteria) this;
		}

		public Criteria andFechacreadoIn(List<String> values) {
			addCriterion("fechaCreado in", values, "fechacreado");
			return (Criteria) this;
		}

		public Criteria andFechacreadoNotIn(List<String> values) {
			addCriterion("fechaCreado not in", values, "fechacreado");
			return (Criteria) this;
		}

		public Criteria andFechacreadoBetween(String value1, String value2) {
			addCriterion("fechaCreado between", value1, value2, "fechacreado");
			return (Criteria) this;
		}

		public Criteria andFechacreadoNotBetween(String value1, String value2) {
			addCriterion("fechaCreado not between", value1, value2,
					"fechacreado");
			return (Criteria) this;
		}

		public Criteria andActivoIsNull() {
			addCriterion("activo is null");
			return (Criteria) this;
		}

		public Criteria andActivoIsNotNull() {
			addCriterion("activo is not null");
			return (Criteria) this;
		}

		public Criteria andActivoEqualTo(Boolean value) {
			addCriterion("activo =", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoNotEqualTo(Boolean value) {
			addCriterion("activo <>", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoGreaterThan(Boolean value) {
			addCriterion("activo >", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoGreaterThanOrEqualTo(Boolean value) {
			addCriterion("activo >=", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoLessThan(Boolean value) {
			addCriterion("activo <", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoLessThanOrEqualTo(Boolean value) {
			addCriterion("activo <=", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoIn(List<Boolean> values) {
			addCriterion("activo in", values, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoNotIn(List<Boolean> values) {
			addCriterion("activo not in", values, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoBetween(Boolean value1, Boolean value2) {
			addCriterion("activo between", value1, value2, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoNotBetween(Boolean value1, Boolean value2) {
			addCriterion("activo not between", value1, value2, "activo");
			return (Criteria) this;
		}

		public Criteria andVisibleIsNull() {
			addCriterion("visible is null");
			return (Criteria) this;
		}

		public Criteria andVisibleIsNotNull() {
			addCriterion("visible is not null");
			return (Criteria) this;
		}

		public Criteria andVisibleEqualTo(Boolean value) {
			addCriterion("visible =", value, "visible");
			return (Criteria) this;
		}

		public Criteria andVisibleNotEqualTo(Boolean value) {
			addCriterion("visible <>", value, "visible");
			return (Criteria) this;
		}

		public Criteria andVisibleGreaterThan(Boolean value) {
			addCriterion("visible >", value, "visible");
			return (Criteria) this;
		}

		public Criteria andVisibleGreaterThanOrEqualTo(Boolean value) {
			addCriterion("visible >=", value, "visible");
			return (Criteria) this;
		}

		public Criteria andVisibleLessThan(Boolean value) {
			addCriterion("visible <", value, "visible");
			return (Criteria) this;
		}

		public Criteria andVisibleLessThanOrEqualTo(Boolean value) {
			addCriterion("visible <=", value, "visible");
			return (Criteria) this;
		}

		public Criteria andVisibleIn(List<Boolean> values) {
			addCriterion("visible in", values, "visible");
			return (Criteria) this;
		}

		public Criteria andVisibleNotIn(List<Boolean> values) {
			addCriterion("visible not in", values, "visible");
			return (Criteria) this;
		}

		public Criteria andVisibleBetween(Boolean value1, Boolean value2) {
			addCriterion("visible between", value1, value2, "visible");
			return (Criteria) this;
		}

		public Criteria andVisibleNotBetween(Boolean value1, Boolean value2) {
			addCriterion("visible not between", value1, value2, "visible");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table proyecto
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table proyecto
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}