package com.pro.proyectospro.configuracion.domain;

public class Proyecto {
	
	private double avance;
	
	private Estado estado;

	public double getAvance() {
		return avance;
	}

	public void setAvance(double avance) {
		this.avance = avance;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proyecto.codigo
	 * @mbggenerated
	 */
	private Integer codigo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proyecto.codPPortafolio
	 * @mbggenerated
	 */
	private Integer codpportafolio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proyecto.nombre
	 * @mbggenerated
	 */
	private String nombre;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proyecto.des
	 * @mbggenerated
	 */
	private String des;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proyecto.desdeCero
	 * @mbggenerated
	 */
	private Boolean desdecero;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proyecto.codEstado
	 * @mbggenerated
	 */
	private Integer codestado;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proyecto.fechaCreado
	 * @mbggenerated
	 */
	private String fechacreado;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proyecto.activo
	 * @mbggenerated
	 */
	private Boolean activo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proyecto.visible
	 * @mbggenerated
	 */
	private Boolean visible;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proyecto.codigo
	 * @return  the value of proyecto.codigo
	 * @mbggenerated
	 */
	public Integer getCodigo() {
		return codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proyecto.codigo
	 * @param codigo  the value for proyecto.codigo
	 * @mbggenerated
	 */
	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proyecto.codPPortafolio
	 * @return  the value of proyecto.codPPortafolio
	 * @mbggenerated
	 */
	public Integer getCodpportafolio() {
		return codpportafolio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proyecto.codPPortafolio
	 * @param codpportafolio  the value for proyecto.codPPortafolio
	 * @mbggenerated
	 */
	public void setCodpportafolio(Integer codpportafolio) {
		this.codpportafolio = codpportafolio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proyecto.nombre
	 * @return  the value of proyecto.nombre
	 * @mbggenerated
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proyecto.nombre
	 * @param nombre  the value for proyecto.nombre
	 * @mbggenerated
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proyecto.des
	 * @return  the value of proyecto.des
	 * @mbggenerated
	 */
	public String getDes() {
		return des;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proyecto.des
	 * @param des  the value for proyecto.des
	 * @mbggenerated
	 */
	public void setDes(String des) {
		this.des = des;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proyecto.desdeCero
	 * @return  the value of proyecto.desdeCero
	 * @mbggenerated
	 */
	public Boolean getDesdecero() {
		return desdecero;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proyecto.desdeCero
	 * @param desdecero  the value for proyecto.desdeCero
	 * @mbggenerated
	 */
	public void setDesdecero(Boolean desdecero) {
		this.desdecero = desdecero;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proyecto.codEstado
	 * @return  the value of proyecto.codEstado
	 * @mbggenerated
	 */
	public Integer getCodestado() {
		return codestado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proyecto.codEstado
	 * @param codestado  the value for proyecto.codEstado
	 * @mbggenerated
	 */
	public void setCodestado(Integer codestado) {
		this.codestado = codestado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proyecto.fechaCreado
	 * @return  the value of proyecto.fechaCreado
	 * @mbggenerated
	 */
	public String getFechacreado() {
		return fechacreado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proyecto.fechaCreado
	 * @param fechacreado  the value for proyecto.fechaCreado
	 * @mbggenerated
	 */
	public void setFechacreado(String fechacreado) {
		this.fechacreado = fechacreado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proyecto.activo
	 * @return  the value of proyecto.activo
	 * @mbggenerated
	 */
	public Boolean getActivo() {
		return activo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proyecto.activo
	 * @param activo  the value for proyecto.activo
	 * @mbggenerated
	 */
	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proyecto.visible
	 * @return  the value of proyecto.visible
	 * @mbggenerated
	 */
	public Boolean getVisible() {
		return visible;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proyecto.visible
	 * @param visible  the value for proyecto.visible
	 * @mbggenerated
	 */
	public void setVisible(Boolean visible) {
		this.visible = visible;
	}

	public Estado getEstado() {
		return estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}
}