package com.pro.proyectospro.configuracion.domain;

public class Recurso {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column recurso.codigo
	 * @mbggenerated
	 */
	private Integer codigo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column recurso.codUsuario
	 * @mbggenerated
	 */
	private Integer codusuario;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column recurso.codDatosPersona
	 * @mbggenerated
	 */
	private Integer coddatospersona;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column recurso.codArea
	 * @mbggenerated
	 */
	private Integer codarea;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column recurso.activo
	 * @mbggenerated
	 */
	private Boolean activo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column recurso.codigo
	 * @return  the value of recurso.codigo
	 * @mbggenerated
	 */
	public Integer getCodigo() {
		return codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column recurso.codigo
	 * @param codigo  the value for recurso.codigo
	 * @mbggenerated
	 */
	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column recurso.codUsuario
	 * @return  the value of recurso.codUsuario
	 * @mbggenerated
	 */
	public Integer getCodusuario() {
		return codusuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column recurso.codUsuario
	 * @param codusuario  the value for recurso.codUsuario
	 * @mbggenerated
	 */
	public void setCodusuario(Integer codusuario) {
		this.codusuario = codusuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column recurso.codDatosPersona
	 * @return  the value of recurso.codDatosPersona
	 * @mbggenerated
	 */
	public Integer getCoddatospersona() {
		return coddatospersona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column recurso.codDatosPersona
	 * @param coddatospersona  the value for recurso.codDatosPersona
	 * @mbggenerated
	 */
	public void setCoddatospersona(Integer coddatospersona) {
		this.coddatospersona = coddatospersona;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column recurso.codArea
	 * @return  the value of recurso.codArea
	 * @mbggenerated
	 */
	public Integer getCodarea() {
		return codarea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column recurso.codArea
	 * @param codarea  the value for recurso.codArea
	 * @mbggenerated
	 */
	public void setCodarea(Integer codarea) {
		this.codarea = codarea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column recurso.activo
	 * @return  the value of recurso.activo
	 * @mbggenerated
	 */
	public Boolean getActivo() {
		return activo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column recurso.activo
	 * @param activo  the value for recurso.activo
	 * @mbggenerated
	 */
	public void setActivo(Boolean activo) {
		this.activo = activo;
	}
}