package com.pro.proyectospro.configuracion.domain;

public class Rol {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rol.codigo
	 * @mbggenerated
	 */
	private Integer codigo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rol.noCodigo
	 * @mbggenerated
	 */
	private String nocodigo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rol.des
	 * @mbggenerated
	 */
	private String des;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rol.activo
	 * @mbggenerated
	 */
	private Boolean activo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rol.codigo
	 * @return  the value of rol.codigo
	 * @mbggenerated
	 */
	public Integer getCodigo() {
		return codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rol.codigo
	 * @param codigo  the value for rol.codigo
	 * @mbggenerated
	 */
	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rol.noCodigo
	 * @return  the value of rol.noCodigo
	 * @mbggenerated
	 */
	public String getNocodigo() {
		return nocodigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rol.noCodigo
	 * @param nocodigo  the value for rol.noCodigo
	 * @mbggenerated
	 */
	public void setNocodigo(String nocodigo) {
		this.nocodigo = nocodigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rol.des
	 * @return  the value of rol.des
	 * @mbggenerated
	 */
	public String getDes() {
		return des;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rol.des
	 * @param des  the value for rol.des
	 * @mbggenerated
	 */
	public void setDes(String des) {
		this.des = des;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rol.activo
	 * @return  the value of rol.activo
	 * @mbggenerated
	 */
	public Boolean getActivo() {
		return activo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rol.activo
	 * @param activo  the value for rol.activo
	 * @mbggenerated
	 */
	public void setActivo(Boolean activo) {
		this.activo = activo;
	}
}