package com.pro.proyectospro.configuracion.domain;

public class Urgencia {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column urgencia.codigo
	 * @mbggenerated
	 */
	private Integer codigo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column urgencia.des
	 * @mbggenerated
	 */
	private String des;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column urgencia.codigo
	 * @return  the value of urgencia.codigo
	 * @mbggenerated
	 */
	public Integer getCodigo() {
		return codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column urgencia.codigo
	 * @param codigo  the value for urgencia.codigo
	 * @mbggenerated
	 */
	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column urgencia.des
	 * @return  the value of urgencia.des
	 * @mbggenerated
	 */
	public String getDes() {
		return des;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column urgencia.des
	 * @param des  the value for urgencia.des
	 * @mbggenerated
	 */
	public void setDes(String des) {
		this.des = des;
	}
}