package com.pro.proyectospro.configuracion.domain;

import java.util.ArrayList;
import java.util.List;

public class UsuarioExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table usuario
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table usuario
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table usuario
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbggenerated
	 */
	public UsuarioExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table usuario
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCodigoIsNull() {
			addCriterion("codigo is null");
			return (Criteria) this;
		}

		public Criteria andCodigoIsNotNull() {
			addCriterion("codigo is not null");
			return (Criteria) this;
		}

		public Criteria andCodigoEqualTo(Integer value) {
			addCriterion("codigo =", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoNotEqualTo(Integer value) {
			addCriterion("codigo <>", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoGreaterThan(Integer value) {
			addCriterion("codigo >", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoGreaterThanOrEqualTo(Integer value) {
			addCriterion("codigo >=", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoLessThan(Integer value) {
			addCriterion("codigo <", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoLessThanOrEqualTo(Integer value) {
			addCriterion("codigo <=", value, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoIn(List<Integer> values) {
			addCriterion("codigo in", values, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoNotIn(List<Integer> values) {
			addCriterion("codigo not in", values, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoBetween(Integer value1, Integer value2) {
			addCriterion("codigo between", value1, value2, "codigo");
			return (Criteria) this;
		}

		public Criteria andCodigoNotBetween(Integer value1, Integer value2) {
			addCriterion("codigo not between", value1, value2, "codigo");
			return (Criteria) this;
		}

		public Criteria andUserIsNull() {
			addCriterion("user is null");
			return (Criteria) this;
		}

		public Criteria andUserIsNotNull() {
			addCriterion("user is not null");
			return (Criteria) this;
		}

		public Criteria andUserEqualTo(String value) {
			addCriterion("user =", value, "user");
			return (Criteria) this;
		}

		public Criteria andUserNotEqualTo(String value) {
			addCriterion("user <>", value, "user");
			return (Criteria) this;
		}

		public Criteria andUserGreaterThan(String value) {
			addCriterion("user >", value, "user");
			return (Criteria) this;
		}

		public Criteria andUserGreaterThanOrEqualTo(String value) {
			addCriterion("user >=", value, "user");
			return (Criteria) this;
		}

		public Criteria andUserLessThan(String value) {
			addCriterion("user <", value, "user");
			return (Criteria) this;
		}

		public Criteria andUserLessThanOrEqualTo(String value) {
			addCriterion("user <=", value, "user");
			return (Criteria) this;
		}

		public Criteria andUserLike(String value) {
			addCriterion("user like", value, "user");
			return (Criteria) this;
		}

		public Criteria andUserNotLike(String value) {
			addCriterion("user not like", value, "user");
			return (Criteria) this;
		}

		public Criteria andUserIn(List<String> values) {
			addCriterion("user in", values, "user");
			return (Criteria) this;
		}

		public Criteria andUserNotIn(List<String> values) {
			addCriterion("user not in", values, "user");
			return (Criteria) this;
		}

		public Criteria andUserBetween(String value1, String value2) {
			addCriterion("user between", value1, value2, "user");
			return (Criteria) this;
		}

		public Criteria andUserNotBetween(String value1, String value2) {
			addCriterion("user not between", value1, value2, "user");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("password is null");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("password is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("password =", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("password <>", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("password >", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("password >=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("password <", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("password <=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("password like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("password not like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordIn(List<String> values) {
			addCriterion("password in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotIn(List<String> values) {
			addCriterion("password not in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("password between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("password not between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPreguntasIsNull() {
			addCriterion("preguntaS is null");
			return (Criteria) this;
		}

		public Criteria andPreguntasIsNotNull() {
			addCriterion("preguntaS is not null");
			return (Criteria) this;
		}

		public Criteria andPreguntasEqualTo(String value) {
			addCriterion("preguntaS =", value, "preguntas");
			return (Criteria) this;
		}

		public Criteria andPreguntasNotEqualTo(String value) {
			addCriterion("preguntaS <>", value, "preguntas");
			return (Criteria) this;
		}

		public Criteria andPreguntasGreaterThan(String value) {
			addCriterion("preguntaS >", value, "preguntas");
			return (Criteria) this;
		}

		public Criteria andPreguntasGreaterThanOrEqualTo(String value) {
			addCriterion("preguntaS >=", value, "preguntas");
			return (Criteria) this;
		}

		public Criteria andPreguntasLessThan(String value) {
			addCriterion("preguntaS <", value, "preguntas");
			return (Criteria) this;
		}

		public Criteria andPreguntasLessThanOrEqualTo(String value) {
			addCriterion("preguntaS <=", value, "preguntas");
			return (Criteria) this;
		}

		public Criteria andPreguntasLike(String value) {
			addCriterion("preguntaS like", value, "preguntas");
			return (Criteria) this;
		}

		public Criteria andPreguntasNotLike(String value) {
			addCriterion("preguntaS not like", value, "preguntas");
			return (Criteria) this;
		}

		public Criteria andPreguntasIn(List<String> values) {
			addCriterion("preguntaS in", values, "preguntas");
			return (Criteria) this;
		}

		public Criteria andPreguntasNotIn(List<String> values) {
			addCriterion("preguntaS not in", values, "preguntas");
			return (Criteria) this;
		}

		public Criteria andPreguntasBetween(String value1, String value2) {
			addCriterion("preguntaS between", value1, value2, "preguntas");
			return (Criteria) this;
		}

		public Criteria andPreguntasNotBetween(String value1, String value2) {
			addCriterion("preguntaS not between", value1, value2, "preguntas");
			return (Criteria) this;
		}

		public Criteria andRespuestasIsNull() {
			addCriterion("respuestaS is null");
			return (Criteria) this;
		}

		public Criteria andRespuestasIsNotNull() {
			addCriterion("respuestaS is not null");
			return (Criteria) this;
		}

		public Criteria andRespuestasEqualTo(String value) {
			addCriterion("respuestaS =", value, "respuestas");
			return (Criteria) this;
		}

		public Criteria andRespuestasNotEqualTo(String value) {
			addCriterion("respuestaS <>", value, "respuestas");
			return (Criteria) this;
		}

		public Criteria andRespuestasGreaterThan(String value) {
			addCriterion("respuestaS >", value, "respuestas");
			return (Criteria) this;
		}

		public Criteria andRespuestasGreaterThanOrEqualTo(String value) {
			addCriterion("respuestaS >=", value, "respuestas");
			return (Criteria) this;
		}

		public Criteria andRespuestasLessThan(String value) {
			addCriterion("respuestaS <", value, "respuestas");
			return (Criteria) this;
		}

		public Criteria andRespuestasLessThanOrEqualTo(String value) {
			addCriterion("respuestaS <=", value, "respuestas");
			return (Criteria) this;
		}

		public Criteria andRespuestasLike(String value) {
			addCriterion("respuestaS like", value, "respuestas");
			return (Criteria) this;
		}

		public Criteria andRespuestasNotLike(String value) {
			addCriterion("respuestaS not like", value, "respuestas");
			return (Criteria) this;
		}

		public Criteria andRespuestasIn(List<String> values) {
			addCriterion("respuestaS in", values, "respuestas");
			return (Criteria) this;
		}

		public Criteria andRespuestasNotIn(List<String> values) {
			addCriterion("respuestaS not in", values, "respuestas");
			return (Criteria) this;
		}

		public Criteria andRespuestasBetween(String value1, String value2) {
			addCriterion("respuestaS between", value1, value2, "respuestas");
			return (Criteria) this;
		}

		public Criteria andRespuestasNotBetween(String value1, String value2) {
			addCriterion("respuestaS not between", value1, value2, "respuestas");
			return (Criteria) this;
		}

		public Criteria andUltimoingresoIsNull() {
			addCriterion("ultimoIngreso is null");
			return (Criteria) this;
		}

		public Criteria andUltimoingresoIsNotNull() {
			addCriterion("ultimoIngreso is not null");
			return (Criteria) this;
		}

		public Criteria andUltimoingresoEqualTo(String value) {
			addCriterion("ultimoIngreso =", value, "ultimoingreso");
			return (Criteria) this;
		}

		public Criteria andUltimoingresoNotEqualTo(String value) {
			addCriterion("ultimoIngreso <>", value, "ultimoingreso");
			return (Criteria) this;
		}

		public Criteria andUltimoingresoGreaterThan(String value) {
			addCriterion("ultimoIngreso >", value, "ultimoingreso");
			return (Criteria) this;
		}

		public Criteria andUltimoingresoGreaterThanOrEqualTo(String value) {
			addCriterion("ultimoIngreso >=", value, "ultimoingreso");
			return (Criteria) this;
		}

		public Criteria andUltimoingresoLessThan(String value) {
			addCriterion("ultimoIngreso <", value, "ultimoingreso");
			return (Criteria) this;
		}

		public Criteria andUltimoingresoLessThanOrEqualTo(String value) {
			addCriterion("ultimoIngreso <=", value, "ultimoingreso");
			return (Criteria) this;
		}

		public Criteria andUltimoingresoIn(List<String> values) {
			addCriterion("ultimoIngreso in", values, "ultimoingreso");
			return (Criteria) this;
		}

		public Criteria andUltimoingresoNotIn(List<String> values) {
			addCriterion("ultimoIngreso not in", values, "ultimoingreso");
			return (Criteria) this;
		}

		public Criteria andUltimoingresoBetween(String value1, String value2) {
			addCriterion("ultimoIngreso between", value1, value2,
					"ultimoingreso");
			return (Criteria) this;
		}

		public Criteria andUltimoingresoNotBetween(String value1, String value2) {
			addCriterion("ultimoIngreso not between", value1, value2,
					"ultimoingreso");
			return (Criteria) this;
		}

		public Criteria andActivoIsNull() {
			addCriterion("activo is null");
			return (Criteria) this;
		}

		public Criteria andActivoIsNotNull() {
			addCriterion("activo is not null");
			return (Criteria) this;
		}

		public Criteria andActivoEqualTo(Boolean value) {
			addCriterion("activo =", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoNotEqualTo(Boolean value) {
			addCriterion("activo <>", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoGreaterThan(Boolean value) {
			addCriterion("activo >", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoGreaterThanOrEqualTo(Boolean value) {
			addCriterion("activo >=", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoLessThan(Boolean value) {
			addCriterion("activo <", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoLessThanOrEqualTo(Boolean value) {
			addCriterion("activo <=", value, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoIn(List<Boolean> values) {
			addCriterion("activo in", values, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoNotIn(List<Boolean> values) {
			addCriterion("activo not in", values, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoBetween(Boolean value1, Boolean value2) {
			addCriterion("activo between", value1, value2, "activo");
			return (Criteria) this;
		}

		public Criteria andActivoNotBetween(Boolean value1, Boolean value2) {
			addCriterion("activo not between", value1, value2, "activo");
			return (Criteria) this;
		}

		public Criteria andFechacreacionIsNull() {
			addCriterion("fechaCreacion is null");
			return (Criteria) this;
		}

		public Criteria andFechacreacionIsNotNull() {
			addCriterion("fechaCreacion is not null");
			return (Criteria) this;
		}

		public Criteria andFechacreacionEqualTo(String value) {
			addCriterion("fechaCreacion =", value, "fechacreacion");
			return (Criteria) this;
		}

		public Criteria andFechacreacionNotEqualTo(String value) {
			addCriterion("fechaCreacion <>", value, "fechacreacion");
			return (Criteria) this;
		}

		public Criteria andFechacreacionGreaterThan(String value) {
			addCriterion("fechaCreacion >", value, "fechacreacion");
			return (Criteria) this;
		}

		public Criteria andFechacreacionGreaterThanOrEqualTo(String value) {
			addCriterion("fechaCreacion >=", value, "fechacreacion");
			return (Criteria) this;
		}

		public Criteria andFechacreacionLessThan(String value) {
			addCriterion("fechaCreacion <", value, "fechacreacion");
			return (Criteria) this;
		}

		public Criteria andFechacreacionLessThanOrEqualTo(String value) {
			addCriterion("fechaCreacion <=", value, "fechacreacion");
			return (Criteria) this;
		}

		public Criteria andFechacreacionIn(List<String> values) {
			addCriterion("fechaCreacion in", values, "fechacreacion");
			return (Criteria) this;
		}

		public Criteria andFechacreacionNotIn(List<String> values) {
			addCriterion("fechaCreacion not in", values, "fechacreacion");
			return (Criteria) this;
		}

		public Criteria andFechacreacionBetween(String value1, String value2) {
			addCriterion("fechaCreacion between", value1, value2,
					"fechacreacion");
			return (Criteria) this;
		}

		public Criteria andFechacreacionNotBetween(String value1, String value2) {
			addCriterion("fechaCreacion not between", value1, value2,
					"fechacreacion");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table usuario
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table usuario
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}