package com.pro.proyectospro.configuracion.domain;

public class Usuario {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuario.codigo
	 * @mbggenerated
	 */
	private Integer codigo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuario.user
	 * @mbggenerated
	 */
	private String user;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuario.password
	 * @mbggenerated
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuario.preguntaS
	 * @mbggenerated
	 */
	private String preguntas;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuario.respuestaS
	 * @mbggenerated
	 */
	private String respuestas;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuario.ultimoIngreso
	 * @mbggenerated
	 */
	private String ultimoingreso;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuario.activo
	 * @mbggenerated
	 */
	private Boolean activo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuario.fechaCreacion
	 * @mbggenerated
	 */
	private String fechacreacion;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuario.codigo
	 * @return  the value of usuario.codigo
	 * @mbggenerated
	 */
	public Integer getCodigo() {
		return codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuario.codigo
	 * @param codigo  the value for usuario.codigo
	 * @mbggenerated
	 */
	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuario.user
	 * @return  the value of usuario.user
	 * @mbggenerated
	 */
	public String getUser() {
		return user;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuario.user
	 * @param user  the value for usuario.user
	 * @mbggenerated
	 */
	public void setUser(String user) {
		this.user = user;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuario.password
	 * @return  the value of usuario.password
	 * @mbggenerated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuario.password
	 * @param password  the value for usuario.password
	 * @mbggenerated
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuario.preguntaS
	 * @return  the value of usuario.preguntaS
	 * @mbggenerated
	 */
	public String getPreguntas() {
		return preguntas;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuario.preguntaS
	 * @param preguntas  the value for usuario.preguntaS
	 * @mbggenerated
	 */
	public void setPreguntas(String preguntas) {
		this.preguntas = preguntas;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuario.respuestaS
	 * @return  the value of usuario.respuestaS
	 * @mbggenerated
	 */
	public String getRespuestas() {
		return respuestas;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuario.respuestaS
	 * @param respuestas  the value for usuario.respuestaS
	 * @mbggenerated
	 */
	public void setRespuestas(String respuestas) {
		this.respuestas = respuestas;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuario.ultimoIngreso
	 * @return  the value of usuario.ultimoIngreso
	 * @mbggenerated
	 */
	public String getUltimoingreso() {
		return ultimoingreso;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuario.ultimoIngreso
	 * @param ultimoingreso  the value for usuario.ultimoIngreso
	 * @mbggenerated
	 */
	public void setUltimoingreso(String ultimoingreso) {
		this.ultimoingreso = ultimoingreso;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuario.activo
	 * @return  the value of usuario.activo
	 * @mbggenerated
	 */
	public Boolean getActivo() {
		return activo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuario.activo
	 * @param activo  the value for usuario.activo
	 * @mbggenerated
	 */
	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuario.fechaCreacion
	 * @return  the value of usuario.fechaCreacion
	 * @mbggenerated
	 */
	public String getFechacreacion() {
		return fechacreacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuario.fechaCreacion
	 * @param fechacreacion  the value for usuario.fechaCreacion
	 * @mbggenerated
	 */
	public void setFechacreacion(String fechacreacion) {
		this.fechacreacion = fechacreacion;
	}
}