package com.pro.proyectospro.configuracion.domain;

public class Usuariorol {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuariorol.codigo
	 * @mbggenerated
	 */
	private Integer codigo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuariorol.codUsuario
	 * @mbggenerated
	 */
	private Integer codusuario;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuariorol.codRol
	 * @mbggenerated
	 */
	private Integer codrol;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column usuariorol.activo
	 * @mbggenerated
	 */
	private Boolean activo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuariorol.codigo
	 * @return  the value of usuariorol.codigo
	 * @mbggenerated
	 */
	public Integer getCodigo() {
		return codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuariorol.codigo
	 * @param codigo  the value for usuariorol.codigo
	 * @mbggenerated
	 */
	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuariorol.codUsuario
	 * @return  the value of usuariorol.codUsuario
	 * @mbggenerated
	 */
	public Integer getCodusuario() {
		return codusuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuariorol.codUsuario
	 * @param codusuario  the value for usuariorol.codUsuario
	 * @mbggenerated
	 */
	public void setCodusuario(Integer codusuario) {
		this.codusuario = codusuario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuariorol.codRol
	 * @return  the value of usuariorol.codRol
	 * @mbggenerated
	 */
	public Integer getCodrol() {
		return codrol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuariorol.codRol
	 * @param codrol  the value for usuariorol.codRol
	 * @mbggenerated
	 */
	public void setCodrol(Integer codrol) {
		this.codrol = codrol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column usuariorol.activo
	 * @return  the value of usuariorol.activo
	 * @mbggenerated
	 */
	public Boolean getActivo() {
		return activo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column usuariorol.activo
	 * @param activo  the value for usuariorol.activo
	 * @mbggenerated
	 */
	public void setActivo(Boolean activo) {
		this.activo = activo;
	}
}