package com.pro.proyectospro.configuracion.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.pro.proyectospro.configuracion.domain.Atarea;
import com.pro.proyectospro.configuracion.domain.AtareaExample;
import com.pro.proyectospro.configuracion.herencia.MyMapper;

public interface AtareaMapper extends MyMapper<Atarea, AtareaExample>{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table atarea
	 * @mbggenerated
	 */
	int countByExample(AtareaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table atarea
	 * @mbggenerated
	 */
	int deleteByExample(AtareaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table atarea
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer codigo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table atarea
	 * @mbggenerated
	 */
	int insert(Atarea record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table atarea
	 * @mbggenerated
	 */
	int insertSelective(Atarea record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table atarea
	 * @mbggenerated
	 */
	List<Atarea> selectByExample(AtareaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table atarea
	 * @mbggenerated
	 */
	Atarea selectByPrimaryKey(Integer codigo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table atarea
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Atarea record,
			@Param("example") AtareaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table atarea
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Atarea record,
			@Param("example") AtareaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table atarea
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Atarea record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table atarea
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Atarea record);
}