package com.pro.proyectospro.configuracion.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.pro.proyectospro.configuracion.domain.Datospersona;
import com.pro.proyectospro.configuracion.domain.DatospersonaExample;
import com.pro.proyectospro.configuracion.herencia.MyMapper;

public interface DatospersonaMapper extends MyMapper<Datospersona, DatospersonaExample>{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table datospersona
	 * @mbggenerated
	 */
	int countByExample(DatospersonaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table datospersona
	 * @mbggenerated
	 */
	int deleteByExample(DatospersonaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table datospersona
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer codigo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table datospersona
	 * @mbggenerated
	 */
	int insert(Datospersona record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table datospersona
	 * @mbggenerated
	 */
	int insertSelective(Datospersona record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table datospersona
	 * @mbggenerated
	 */
	List<Datospersona> selectByExample(DatospersonaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table datospersona
	 * @mbggenerated
	 */
	Datospersona selectByPrimaryKey(Integer codigo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table datospersona
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Datospersona record,
			@Param("example") DatospersonaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table datospersona
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Datospersona record,
			@Param("example") DatospersonaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table datospersona
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Datospersona record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table datospersona
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Datospersona record);
}