package com.pro.proyectospro.configuracion.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.pro.proyectospro.configuracion.domain.Estado;
import com.pro.proyectospro.configuracion.domain.EstadoExample;
import com.pro.proyectospro.configuracion.herencia.MyMapper;

public interface EstadoMapper extends MyMapper<Estado, EstadoExample> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table estado
	 * @mbggenerated
	 */
	int countByExample(EstadoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table estado
	 * @mbggenerated
	 */
	int deleteByExample(EstadoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table estado
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer codigo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table estado
	 * @mbggenerated
	 */
	int insert(Estado record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table estado
	 * @mbggenerated
	 */
	int insertSelective(Estado record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table estado
	 * @mbggenerated
	 */
	List<Estado> selectByExample(EstadoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table estado
	 * @mbggenerated
	 */
	Estado selectByPrimaryKey(Integer codigo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table estado
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Estado record,
			@Param("example") EstadoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table estado
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Estado record,
			@Param("example") EstadoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table estado
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Estado record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table estado
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Estado record);
}