package com.pro.proyectospro.configuracion.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.pro.proyectospro.configuracion.domain.Interesado;
import com.pro.proyectospro.configuracion.domain.InteresadoExample;
import com.pro.proyectospro.configuracion.herencia.MyMapper;

public interface InteresadoMapper extends MyMapper<Interesado, InteresadoExample>{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interesado
	 * @mbggenerated
	 */
	int countByExample(InteresadoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interesado
	 * @mbggenerated
	 */
	int deleteByExample(InteresadoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interesado
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer codigo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interesado
	 * @mbggenerated
	 */
	int insert(Interesado record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interesado
	 * @mbggenerated
	 */
	int insertSelective(Interesado record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interesado
	 * @mbggenerated
	 */
	List<Interesado> selectByExample(InteresadoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interesado
	 * @mbggenerated
	 */
	Interesado selectByPrimaryKey(Integer codigo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interesado
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Interesado record,
			@Param("example") InteresadoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interesado
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Interesado record,
			@Param("example") InteresadoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interesado
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Interesado record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table interesado
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Interesado record);
}