package com.pro.proyectospro.configuracion.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.pro.proyectospro.configuracion.domain.Pdocumento;
import com.pro.proyectospro.configuracion.domain.PdocumentoExample;
import com.pro.proyectospro.configuracion.herencia.MyMapper;

public interface PdocumentoMapper extends MyMapper<Pdocumento, PdocumentoExample>{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdocumento
	 * @mbggenerated
	 */
	int countByExample(PdocumentoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdocumento
	 * @mbggenerated
	 */
	int deleteByExample(PdocumentoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdocumento
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer codigo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdocumento
	 * @mbggenerated
	 */
	int insert(Pdocumento record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdocumento
	 * @mbggenerated
	 */
	int insertSelective(Pdocumento record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdocumento
	 * @mbggenerated
	 */
	List<Pdocumento> selectByExample(PdocumentoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdocumento
	 * @mbggenerated
	 */
	Pdocumento selectByPrimaryKey(Integer codigo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdocumento
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Pdocumento record,
			@Param("example") PdocumentoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdocumento
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Pdocumento record,
			@Param("example") PdocumentoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdocumento
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Pdocumento record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdocumento
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Pdocumento record);
}