package com.pro.proyectospro.configuracion.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.pro.proyectospro.configuracion.domain.Pincidencia;
import com.pro.proyectospro.configuracion.domain.PincidenciaExample;
import com.pro.proyectospro.configuracion.herencia.MyMapper;

public interface PincidenciaMapper extends MyMapper<Pincidencia, PincidenciaExample> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pincidencia
	 * @mbggenerated
	 */
	int countByExample(PincidenciaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pincidencia
	 * @mbggenerated
	 */
	int deleteByExample(PincidenciaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pincidencia
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer codigo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pincidencia
	 * @mbggenerated
	 */
	int insert(Pincidencia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pincidencia
	 * @mbggenerated
	 */
	int insertSelective(Pincidencia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pincidencia
	 * @mbggenerated
	 */
	List<Pincidencia> selectByExample(PincidenciaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pincidencia
	 * @mbggenerated
	 */
	Pincidencia selectByPrimaryKey(Integer codigo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pincidencia
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Pincidencia record,
			@Param("example") PincidenciaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pincidencia
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Pincidencia record,
			@Param("example") PincidenciaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pincidencia
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Pincidencia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pincidencia
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Pincidencia record);
}