package com.pro.proyectospro.configuracion.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.pro.proyectospro.configuracion.domain.Pmanager;
import com.pro.proyectospro.configuracion.domain.PmanagerExample;
import com.pro.proyectospro.configuracion.herencia.MyMapper;

public interface PmanagerMapper extends MyMapper<Pmanager, PmanagerExample>{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pmanager
	 * @mbggenerated
	 */
	int countByExample(PmanagerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pmanager
	 * @mbggenerated
	 */
	int deleteByExample(PmanagerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pmanager
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer codigo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pmanager
	 * @mbggenerated
	 */
	int insert(Pmanager record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pmanager
	 * @mbggenerated
	 */
	int insertSelective(Pmanager record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pmanager
	 * @mbggenerated
	 */
	List<Pmanager> selectByExample(PmanagerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pmanager
	 * @mbggenerated
	 */
	Pmanager selectByPrimaryKey(Integer codigo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pmanager
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Pmanager record,
			@Param("example") PmanagerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pmanager
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Pmanager record,
			@Param("example") PmanagerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pmanager
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Pmanager record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pmanager
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Pmanager record);
}