package com.pro.proyectospro.configuracion.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.pro.proyectospro.configuracion.domain.Pmanagerproyecto;
import com.pro.proyectospro.configuracion.domain.PmanagerproyectoExample;
import com.pro.proyectospro.configuracion.herencia.MyMapper;

public interface PmanagerproyectoMapper extends MyMapper<Pmanagerproyecto, PmanagerproyectoExample> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pmanagerproyecto
	 * @mbggenerated
	 */
	int countByExample(PmanagerproyectoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pmanagerproyecto
	 * @mbggenerated
	 */
	int deleteByExample(PmanagerproyectoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pmanagerproyecto
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer codigo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pmanagerproyecto
	 * @mbggenerated
	 */
	int insert(Pmanagerproyecto record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pmanagerproyecto
	 * @mbggenerated
	 */
	int insertSelective(Pmanagerproyecto record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pmanagerproyecto
	 * @mbggenerated
	 */
	List<Pmanagerproyecto> selectByExample(PmanagerproyectoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pmanagerproyecto
	 * @mbggenerated
	 */
	Pmanagerproyecto selectByPrimaryKey(Integer codigo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pmanagerproyecto
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Pmanagerproyecto record,
			@Param("example") PmanagerproyectoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pmanagerproyecto
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Pmanagerproyecto record,
			@Param("example") PmanagerproyectoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pmanagerproyecto
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Pmanagerproyecto record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pmanagerproyecto
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Pmanagerproyecto record);
}