package com.pro.proyectospro.configuracion.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.pro.proyectospro.configuracion.domain.Portafolio;
import com.pro.proyectospro.configuracion.domain.PortafolioExample;
import com.pro.proyectospro.configuracion.herencia.MyMapper;

public interface PortafolioMapper extends MyMapper<Portafolio, PortafolioExample> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portafolio
	 * @mbggenerated
	 */
	int countByExample(PortafolioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portafolio
	 * @mbggenerated
	 */
	int deleteByExample(PortafolioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portafolio
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer codigo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portafolio
	 * @mbggenerated
	 */
	int insert(Portafolio record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portafolio
	 * @mbggenerated
	 */
	int insertSelective(Portafolio record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portafolio
	 * @mbggenerated
	 */
	List<Portafolio> selectByExample(PortafolioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portafolio
	 * @mbggenerated
	 */
	Portafolio selectByPrimaryKey(Integer codigo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portafolio
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Portafolio record,
			@Param("example") PortafolioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portafolio
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Portafolio record,
			@Param("example") PortafolioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portafolio
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Portafolio record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table portafolio
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Portafolio record);
}