package com.pro.proyectospro.configuracion.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.pro.proyectospro.configuracion.domain.Proyecto;
import com.pro.proyectospro.configuracion.domain.ProyectoExample;
import com.pro.proyectospro.configuracion.herencia.MyMapper;

public interface ProyectoMapper extends MyMapper<Proyecto, ProyectoExample> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proyecto
	 * @mbggenerated
	 */
	int countByExample(ProyectoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proyecto
	 * @mbggenerated
	 */
	int deleteByExample(ProyectoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proyecto
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer codigo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proyecto
	 * @mbggenerated
	 */
	int insert(Proyecto record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proyecto
	 * @mbggenerated
	 */
	int insertSelective(Proyecto record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proyecto
	 * @mbggenerated
	 */
	List<Proyecto> selectByExample(ProyectoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proyecto
	 * @mbggenerated
	 */
	Proyecto selectByPrimaryKey(Integer codigo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proyecto
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Proyecto record,
			@Param("example") ProyectoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proyecto
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Proyecto record,
			@Param("example") ProyectoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proyecto
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Proyecto record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table proyecto
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Proyecto record);
}