package com.pro.proyectospro.configuracion.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.pro.proyectospro.configuracion.domain.Recurso;
import com.pro.proyectospro.configuracion.domain.RecursoExample;
import com.pro.proyectospro.configuracion.herencia.MyMapper;

public interface RecursoMapper extends MyMapper<Recurso, RecursoExample>{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recurso
	 * @mbggenerated
	 */
	int countByExample(RecursoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recurso
	 * @mbggenerated
	 */
	int deleteByExample(RecursoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recurso
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer codigo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recurso
	 * @mbggenerated
	 */
	int insert(Recurso record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recurso
	 * @mbggenerated
	 */
	int insertSelective(Recurso record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recurso
	 * @mbggenerated
	 */
	List<Recurso> selectByExample(RecursoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recurso
	 * @mbggenerated
	 */
	Recurso selectByPrimaryKey(Integer codigo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recurso
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Recurso record,
			@Param("example") RecursoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recurso
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Recurso record,
			@Param("example") RecursoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recurso
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Recurso record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recurso
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Recurso record);
}