	package com.pro.proyectospro.configuracion.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.pro.proyectospro.configuracion.domain.Supervisor;
import com.pro.proyectospro.configuracion.domain.SupervisorExample;
import com.pro.proyectospro.configuracion.herencia.MyMapper;

public interface SupervisorMapper extends MyMapper<Supervisor, SupervisorExample>{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supervisor
	 * @mbggenerated
	 */
	int countByExample(SupervisorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supervisor
	 * @mbggenerated
	 */
	int deleteByExample(SupervisorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supervisor
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer codigo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supervisor
	 * @mbggenerated
	 */
	int insert(Supervisor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supervisor
	 * @mbggenerated
	 */
	int insertSelective(Supervisor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supervisor
	 * @mbggenerated
	 */
	List<Supervisor> selectByExample(SupervisorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supervisor
	 * @mbggenerated
	 */
	Supervisor selectByPrimaryKey(Integer codigo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supervisor
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Supervisor record,
			@Param("example") SupervisorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supervisor
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Supervisor record,
			@Param("example") SupervisorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supervisor
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Supervisor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supervisor
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Supervisor record);
}