package com.pro.proyectospro.configuracion.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.pro.proyectospro.configuracion.domain.Tarea;
import com.pro.proyectospro.configuracion.domain.TareaExample;
import com.pro.proyectospro.configuracion.herencia.MyMapper;

public interface TareaMapper extends MyMapper<Tarea, TareaExample> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tarea
	 * @mbggenerated
	 */
	int countByExample(TareaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tarea
	 * @mbggenerated
	 */
	int deleteByExample(TareaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tarea
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer codigo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tarea
	 * @mbggenerated
	 */
	int insert(Tarea record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tarea
	 * @mbggenerated
	 */
	int insertSelective(Tarea record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tarea
	 * @mbggenerated
	 */
	List<Tarea> selectByExample(TareaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tarea
	 * @mbggenerated
	 */
	Tarea selectByPrimaryKey(Integer codigo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tarea
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Tarea record,
			@Param("example") TareaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tarea
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Tarea record,
			@Param("example") TareaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tarea
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Tarea record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tarea
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Tarea record);
}