package com.pro.proyectospro.configuracion.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.pro.proyectospro.configuracion.domain.Urgencia;
import com.pro.proyectospro.configuracion.domain.UrgenciaExample;
import com.pro.proyectospro.configuracion.herencia.MyMapper;

public interface UrgenciaMapper extends MyMapper<Urgencia, UrgenciaExample>{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table urgencia
	 * @mbggenerated
	 */
	int countByExample(UrgenciaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table urgencia
	 * @mbggenerated
	 */
	int deleteByExample(UrgenciaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table urgencia
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer codigo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table urgencia
	 * @mbggenerated
	 */
	int insert(Urgencia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table urgencia
	 * @mbggenerated
	 */
	int insertSelective(Urgencia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table urgencia
	 * @mbggenerated
	 */
	List<Urgencia> selectByExample(UrgenciaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table urgencia
	 * @mbggenerated
	 */
	Urgencia selectByPrimaryKey(Integer codigo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table urgencia
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Urgencia record,
			@Param("example") UrgenciaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table urgencia
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Urgencia record,
			@Param("example") UrgenciaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table urgencia
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Urgencia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table urgencia
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Urgencia record);
}