package com.pro.proyectospro.configuracion.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.pro.proyectospro.configuracion.domain.Usuario;
import com.pro.proyectospro.configuracion.domain.UsuarioExample;
import com.pro.proyectospro.configuracion.herencia.MyMapper;

public interface UsuarioMapper extends MyMapper<Usuario, UsuarioExample>{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbggenerated
	 */
	int countByExample(UsuarioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbggenerated
	 */
	int deleteByExample(UsuarioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer codigo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbggenerated
	 */
	int insert(Usuario record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbggenerated
	 */
	int insertSelective(Usuario record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbggenerated
	 */
	List<Usuario> selectByExample(UsuarioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbggenerated
	 */
	Usuario selectByPrimaryKey(Integer codigo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Usuario record,
			@Param("example") UsuarioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Usuario record,
			@Param("example") UsuarioExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Usuario record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuario
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Usuario record);
}