package com.pro.proyectospro.configuracion.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.pro.proyectospro.configuracion.domain.Usuariorol;
import com.pro.proyectospro.configuracion.domain.UsuariorolExample;
import com.pro.proyectospro.configuracion.herencia.MyMapper;

public interface UsuariorolMapper extends MyMapper<Usuariorol, UsuariorolExample>{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuariorol
	 * @mbggenerated
	 */
	int countByExample(UsuariorolExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuariorol
	 * @mbggenerated
	 */
	int deleteByExample(UsuariorolExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuariorol
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer codigo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuariorol
	 * @mbggenerated
	 */
	int insert(Usuariorol record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuariorol
	 * @mbggenerated
	 */
	int insertSelective(Usuariorol record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuariorol
	 * @mbggenerated
	 */
	List<Usuariorol> selectByExample(UsuariorolExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuariorol
	 * @mbggenerated
	 */
	Usuariorol selectByPrimaryKey(Integer codigo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuariorol
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Usuariorol record,
			@Param("example") UsuariorolExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuariorol
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Usuariorol record,
			@Param("example") UsuariorolExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuariorol
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Usuariorol record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table usuariorol
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Usuariorol record);
}